{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.6.0-SNAPSHOT/kotlinx-serialization-properties-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-iosarm32-1.6.0-SNAPSHOT.klib",
          "size": 19606,
          "sha512": "e716a6dea4ebda47c2b1025ba384197d2c8746c8502de9a8aa213da76ae74059cf8a9243f276f5d8c4d2ce5576e4d63a0cca9035ba7f461b0c5d1ad1846cf34b",
          "sha256": "7f9fa19c23208c3f4d283a9e9392ef6ddeb9abe000f1b81ebfc31f186a7ee586",
          "sha1": "4f9050c7136b1ca310680dc50e7fc7912219ddf4",
          "md5": "cf816bdc9a613ccbdff53a8e37d1b1c5"
        }
      ]
    },
    {
      "name": "iosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-iosarm32-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-iosarm32-1.6.0-SNAPSHOT-sources.jar",
          "size": 3766,
          "sha512": "a5bd31251a9c5283b9ee19bfccdab80225e5a9308307d07b0ac81d9950c9c08123c2dab9a208588943b7e7b08c3c9214017a378bc7c89fc0806edba717461b90",
          "sha256": "6271ba0299d4710db9c9bb890166eb8011dfe605ac60bb35043106e60971e815",
          "sha1": "1453a245d2574f74898d4f20b6f97b889b303660",
          "md5": "632184f558a1323015aa2d74c57bc53e"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-iosarm32-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-iosarm32-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "80545b0792a4d401b4d9d3fa777f5aaaf2a5cdc82b6226862e3e002bfb0e43bf78b64ea85d9bbdd09e57318c8fb291c9dcf84417d639f99d761c7606859b0134",
          "sha256": "c5f2b51b6fee3ae708110ae52d67aac99283e9afd866af2b12c9d2cb1f969263",
          "sha1": "2cb5477ebf290137c7c96095e4043953210a21c4",
          "md5": "17e8a6108ae9dc18ae4de61964928261"
        }
      ]
    }
  ]
}
