{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.7.1-SNAPSHOT/kotlinx-serialization-properties-1.7.1-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-macosarm64-1.7.1-SNAPSHOT.klib",
          "size": 18778,
          "sha512": "91e7bae0e22a244feae9d7b759a30b1a509ee63dc0e77ee9030466fa5019acb01add37d6b703a807d588ed21d557be12cb24d713ed910973f5da02826773bd4f",
          "sha256": "d27bdca5eb6019981a2697ef80a7787fee607b091389c00b08b02a90261643ce",
          "sha1": "3829b70608999d3fef5f42b1817aa451c7e2eb8b",
          "md5": "ddc53c166e130f13c7a6bb4c92c32326"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-macosarm64-1.7.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-macosarm64-1.7.1-SNAPSHOT-sources.jar",
          "size": 3692,
          "sha512": "59ddd7439185a552035f7e09e3bad84e212673bb218ba42b003ad79be221ffa9a231f4738de5eeb9a7a9955fcb9869ddd72958896104f6c7654afda9dfa4eecd",
          "sha256": "f0edaa0a99e24d8a9953ea734b3eb78428ec949dd568e1eb7125e604e6714831",
          "sha1": "0f16141a0888abd29bba2d9cd82aa4230daa7275",
          "md5": "1f1a044c083221b07767f71927933221"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-macosarm64-1.7.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-macosarm64-1.7.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "31186e2b5c5fc7a22fe92075d4254e9779924ce9abb62f1bb7ed006929d82e7064fa4ccb288bf29933c1af5f808f12ef143f02029cad148e19ae89148b43bf69",
          "sha256": "9f9a9aaa2d8769f5393baddd0f846c164a23f02145b0103f50c9eb3295888fb1",
          "sha1": "462bc072073b6951c7ec2a2ed58b3aeceb683012",
          "md5": "40a8aec1eda0f675c5c138f89dd16f59"
        }
      ]
    }
  ]
}
