{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.7.1-SNAPSHOT/kotlinx-serialization-json-1.7.1-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-mingwx64-1.7.1-SNAPSHOT.klib",
          "size": 300025,
          "sha512": "dcffa563b62bc0a4140b0b6bb02721d5a0694fb1b9b68ee20ac90530bae8313c2833450c430848e12f00ac9a33062a391593fac0d67ca3d747d9fea4002c68ea",
          "sha256": "7b8c3e882b705e996368872098d190c54f5fce4e07703f07180d08cfd9ed946e",
          "sha1": "ca7b339c4e5ea08a589da6a8180dd2ed3c48a463",
          "md5": "2fc87ef0a35f212bd7331c4e0eb3a3f4"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-mingwx64-1.7.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-mingwx64-1.7.1-SNAPSHOT-sources.jar",
          "size": 81199,
          "sha512": "905f6eeee1f702a18d953b628d95f4c8a3004cfc4208e9d17bb5ed4019b9317c685bd28c30818c47bd7015ab60527eaa12a3053eadd0ea464df3f23e984bab58",
          "sha256": "c38901a62bed97faea04105a47cc01a679de17c18d76d34a899a959a689f1030",
          "sha1": "da227f844c06ddba53c4e4b969beb3272d4977fb",
          "md5": "bea0bff577edd697079dd925410d272f"
        }
      ]
    }
  ]
}
