{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.6.0-SNAPSHOT/kotlinx-serialization-protobuf-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jvm-1.6.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-protobuf-jvm-1.6.0-SNAPSHOT.jar",
          "size": 101876,
          "sha512": "7f053d32b495e76ab329a7ae8913957cd2589678e0c5c93ea3c5b4c0dc80ba1d704e8892678963728bcf2feb26696f01c00a933e4a1f2482ceb291b0298c0ae5",
          "sha256": "837b836353bbac26729cf4085b226df442154171f115b11ef22c1a9a8bc2372d",
          "sha1": "a311b8ffbbf78147ed80d630237c0d414768468e",
          "md5": "2b87c6209a4628d5c2f31df81ddc99fe"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jvm-1.6.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-protobuf-jvm-1.6.0-SNAPSHOT.jar",
          "size": 101876,
          "sha512": "7f053d32b495e76ab329a7ae8913957cd2589678e0c5c93ea3c5b4c0dc80ba1d704e8892678963728bcf2feb26696f01c00a933e4a1f2482ceb291b0298c0ae5",
          "sha256": "837b836353bbac26729cf4085b226df442154171f115b11ef22c1a9a8bc2372d",
          "sha1": "a311b8ffbbf78147ed80d630237c0d414768468e",
          "md5": "2b87c6209a4628d5c2f31df81ddc99fe"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-jvm-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-protobuf-jvm-1.6.0-SNAPSHOT-sources.jar",
          "size": 28453,
          "sha512": "000e5bfec886307b92a92795ad50dd201652fd8f0e2dad5d2fe16758cb856b3e5fa0fb3ec20c71a57b186d965b4d2ff5fed00a1bb12812c57a86683613954888",
          "sha256": "41de84250610dad7a7b57f199d507adbfd52efe134fd671b297a59604031ad5a",
          "sha1": "16ec4134fb07341250251c7004e213dae4491dea",
          "md5": "f42d6eb4667d35987c9c0149e4abd97f"
        }
      ]
    }
  ]
}
