{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.6.0-SNAPSHOT/kotlinx-serialization-json-okio-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio.klib",
          "url": "kotlinx-serialization-json-okio-macosarm64-1.6.0-SNAPSHOT.klib",
          "size": 15817,
          "sha512": "b9f044cc746d63084336987e1db3d00f2390edd4d1e96f6e75606169f8558e73078e3f15dbadaed7cb9d257ba8cc115287350173cfed315bd90c739dca5933df",
          "sha256": "a999ed049d7e3409ae463b3162fa1180cbea0e1474c365836e256ccfb57ef3da",
          "sha1": "a093e4acadd0b935085ba68039edd562d6c25b52",
          "md5": "a3b8dafa12b547c008c4a5e562290b65"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-macosarm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-okio-macosarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 4225,
          "sha512": "69283b909b2852f8174e5ef5ed5b288a478ce87980324c79bf800bc19b3aeaf113398ca22e4e8ac8299c5f0abbe4469d63b9f294c12e889659681763198e0e00",
          "sha256": "9728b0f43cfac52ea29b95eda581063d931d8c4e254585a5f010ec029e728697",
          "sha1": "01c2d3cd35733345c5c9b0a3d3d20f8de1fd4cd6",
          "md5": "afe1cf472b04904974de1ac0ad99e35e"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-macosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-okio-macosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6f6f49ce58d4d6fdb636cdc002a81a56b909664cee550e77569b3a5ce443711c17bb3ea8c363f93301c79b1f58383f1a57f3638d37463932810eeb3d9432812d",
          "sha256": "cfcf0c8a1ce1215239182a9e2598ed6d40ad1fb454848a2c60c7415d9873ce47",
          "sha1": "584b6cb3268e44bd9f8922d766b7f34cf79f247c",
          "md5": "e8e7031754d353d3a729923af809fde7"
        }
      ]
    }
  ]
}
