{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.6.0-SNAPSHOT/kotlinx-serialization-json-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-tvosarm64-1.6.0-SNAPSHOT.klib",
          "size": 247673,
          "sha512": "4319aa261610e84c8956a3bf2323703eb31c2651411ee6aab18774b6bf0abad302407d53f2c67092f8727d2bbe474d637709eaccca56fe41f7a688c67c40f2a6",
          "sha256": "2f746583909133cc317daad2fe589d7e3d997433525482641f2f6eb2d1763840",
          "sha1": "e8534576e8a163e2bbe560d55c309a6bce9add54",
          "md5": "531541c881051118390fc3060547fceb"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-tvosarm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-tvosarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 73593,
          "sha512": "111f3c2443dbb3cb6537b5d9a92597b6c8b2bf9616833587dddfe2e80ccaf151d60b2201e7f535d22204a37cd56b0edde1a979eb6bd80b21f82bcfc03164f876",
          "sha256": "4b7dd8d46dd54a8f249db397553d290f77b5468477c849d25f8d6c4d52ca7e33",
          "sha1": "1d13131e61139f51287f933b0583331d3726e9e2",
          "md5": "bcc17f5e8e9f5b4f6e5d6dd5a816f90c"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-tvosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-tvosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ce76d42d0677bcd8cc662bb48b076c2c6dff304319458bec01d5e2519e19f1b090b77105295ed192c30d35c5d09901858fa6b7526502e7235af49ca6ad359cff",
          "sha256": "cc4aa7ae7b04d49a119a02c7a94d6ad1870a175d7f273424f3f479cc587f799c",
          "sha1": "d4e98ef0fe8b18b2ba02019bde6b8a2d97bc3fe9",
          "md5": "1a6db76e49923d721e8d6924036baf64"
        }
      ]
    }
  ]
}
