{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.7.2-SNAPSHOT/kotlinx-serialization-cbor-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jvm-1.7.2-SNAPSHOT.jar",
          "url": "kotlinx-serialization-cbor-jvm-1.7.2-SNAPSHOT.jar",
          "size": 66598,
          "sha512": "8e844aa56b3ada9662879fe66ea41df775f7a87a89e3468e1c7cc39de389be8827c4741ab0bfefdf393d192063c74f889fe9b2b11100dac0dbda0b0d95eb33e5",
          "sha256": "b518b8af00abad6525f675a07dac63d4b9b974a30d983596e94e5f0f197ea783",
          "sha1": "b36f4368d3667d8208c5c04b56e46cf04603c098",
          "md5": "9da3d3bbb2ccc145a5037c16288be4ee"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jvm-1.7.2-SNAPSHOT.jar",
          "url": "kotlinx-serialization-cbor-jvm-1.7.2-SNAPSHOT.jar",
          "size": 66598,
          "sha512": "8e844aa56b3ada9662879fe66ea41df775f7a87a89e3468e1c7cc39de389be8827c4741ab0bfefdf393d192063c74f889fe9b2b11100dac0dbda0b0d95eb33e5",
          "sha256": "b518b8af00abad6525f675a07dac63d4b9b974a30d983596e94e5f0f197ea783",
          "sha1": "b36f4368d3667d8208c5c04b56e46cf04603c098",
          "md5": "9da3d3bbb2ccc145a5037c16288be4ee"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-jvm-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-jvm-1.7.2-SNAPSHOT-sources.jar",
          "size": 19425,
          "sha512": "ffb1f6d8a03d975913e47a3b3294ac160b40497e9dc09c1851d8153136829678891b8f25e853f026c5bba13bd1cf683d32bb856d2cb5cfcc910d9fa59fb59558",
          "sha256": "c137c04407f379f0a1bfc3b98b5a5aa8b7dfbce5017e369b6613340b58a49e50",
          "sha1": "c0245c967deffe9275fd9240d005f1788f7597d4",
          "md5": "d2ffde2434a3f49dbe0c66fcd21a4768"
        }
      ]
    }
  ]
}
