{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.6.3-SNAPSHOT/kotlinx-serialization-cbor-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-iosarm64-1.6.3-SNAPSHOT.klib",
          "size": 94375,
          "sha512": "d812b56cb63f69e1939dde85b87c96b10f34c97d1c74d7eda063aa3ab3ab99babb6b315822aa4a47b080097b2e9d61c20ad9d7d5eaa44d5bd6d90b3bdb220646",
          "sha256": "3a397dfd68fdf266365d3e72b2d00e6e1c195120c7a70d32ef088f591aa1a613",
          "sha1": "2134fa2ce84214805e4f28fb8d5211de1a75a532",
          "md5": "79b1a4c88110b50369782511f59270ee"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-iosarm64-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-iosarm64-1.6.3-SNAPSHOT-sources.jar",
          "size": 18803,
          "sha512": "b65500aabedc36290e381486cf16578212f19590a8dc6d904016561ce38c33a60d5ca4b6de0967aeab7ff453641e918433e8e378ce1cca381140b54cad2f218a",
          "sha256": "2690bfe0edf3cd4248a5f83b33da243aa1c48059e343af827fad7015b5c7546b",
          "sha1": "d3a66e03399f1509de27d127795c434227b6e86f",
          "md5": "d88d9a67fa0303780d9f120eb7cf078c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-iosarm64-1.6.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-cbor-iosarm64-1.6.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "2f4b0849f46cdbee4514f966f15e084a93f7e9e14cf113a5ca9d0f1cadaa4c52faae97054cdbeaaa41ca24dace61a8598958729243989e8c25f55b2c936e3150",
          "sha256": "3a69be67f90b712dd9580cab2cf4ba354df25a63ed462499fac3a98998c30ec3",
          "sha1": "75502acf3d18e9fb0d83958edfc546d1d48c31a5",
          "md5": "618f8f32ef2ad506e179db3249aae46b"
        }
      ]
    }
  ]
}
