{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.6.3-SNAPSHOT/kotlinx-serialization-protobuf-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-wasm-js-1.6.3-SNAPSHOT.klib",
          "url": "kotlinx-serialization-protobuf-wasm-js-1.6.3-SNAPSHOT.klib",
          "size": 132886,
          "sha512": "67bdf77d4d4624a97159e1f08a265081f73c1d5647fcc875849e62e9315f265d79c36cb91fce14aac1aca838c0906b9486688cd79156480d4eaca8941826e0bc",
          "sha256": "117896be693018632f17f7061d0602131020b5e6777fa4b8f0913102f3a0f445",
          "sha1": "1fc90637c6f03d30a94e1fef88ebaded7d1dfc8c",
          "md5": "9f891c73d2c53c5757b98f96dea9929b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-wasm-js-1.6.3-SNAPSHOT.klib",
          "url": "kotlinx-serialization-protobuf-wasm-js-1.6.3-SNAPSHOT.klib",
          "size": 132886,
          "sha512": "67bdf77d4d4624a97159e1f08a265081f73c1d5647fcc875849e62e9315f265d79c36cb91fce14aac1aca838c0906b9486688cd79156480d4eaca8941826e0bc",
          "sha256": "117896be693018632f17f7061d0602131020b5e6777fa4b8f0913102f3a0f445",
          "sha1": "1fc90637c6f03d30a94e1fef88ebaded7d1dfc8c",
          "md5": "9f891c73d2c53c5757b98f96dea9929b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-wasm-js-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-protobuf-wasm-js-1.6.3-SNAPSHOT-sources.jar",
          "size": 28531,
          "sha512": "b4ff5d3591f251fe34bb9d1b724dd34b1afd2745293037cb133efa770184d583dc7cb74fa29bdc950e670c9a8f24c49d64601a723acf3df27d23c15687c6eb8d",
          "sha256": "c635a2f6163146171f539e654e78c486f6bd189602780a0c664836556fb6cda8",
          "sha1": "e4d6c94185a9ebbd7757278f8c073391ec865b56",
          "md5": "cbac044474a7b3cb0dfc7d3a8343d4e8"
        }
      ]
    }
  ]
}
