{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.8.0-SNAPSHOT/kotlinx-serialization-json-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-js-1.8.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-js-1.8.0-SNAPSHOT.klib",
          "size": 339965,
          "sha512": "f766c71b61593a95c11f0ed280bff8bb15cacc999570498a8d280e07254f651fa2d70fd6897ff8ca7759a189fda689d808de1f33eaecf9511e56985d4db9153d",
          "sha256": "7cb0a10857d1486aec3718b58e9acf0346ca46a118e30060892cc28bfea97fd8",
          "sha1": "a8e97732eaaabf78d22031f2c741a36d55fd7dd0",
          "md5": "08f68ee514bfebf365eeba979a57d2f6"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-js-1.8.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-js-1.8.0-SNAPSHOT.klib",
          "size": 339965,
          "sha512": "f766c71b61593a95c11f0ed280bff8bb15cacc999570498a8d280e07254f651fa2d70fd6897ff8ca7759a189fda689d808de1f33eaecf9511e56985d4db9153d",
          "sha256": "7cb0a10857d1486aec3718b58e9acf0346ca46a118e30060892cc28bfea97fd8",
          "sha1": "a8e97732eaaabf78d22031f2c741a36d55fd7dd0",
          "md5": "08f68ee514bfebf365eeba979a57d2f6"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-js-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-js-1.8.0-SNAPSHOT-sources.jar",
          "size": 89549,
          "sha512": "e31a7b66be00190400277dee5d2bf119ebf64dfc0e9121cf1659db3f00561019d0c00afd0ab2978809dc3634b069910004a7c4b6c560ba6e04d67942ffa3c8fd",
          "sha256": "7e1821204a6e5f89a65c5273f82502b7dd1805b6d74357999e61bdc3517d2bbf",
          "sha1": "d4b26fe36b6a6fdd99fa3d5deef38236ceed551c",
          "md5": "7689153fb5de5ce71d04b52e4502721a"
        }
      ]
    }
  ]
}
