{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.6.0-SNAPSHOT/kotlinx-serialization-json-okio-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio.klib",
          "url": "kotlinx-serialization-json-okio-watchosarm64-1.6.0-SNAPSHOT.klib",
          "size": 15745,
          "sha512": "9fe920ea17721f888e52b65dc3a666a9aefd88432ab817ba6f931be0fda7c2dba06885a4d0029c5d586be598182751852cb2223f84794b04a03a5ab0424ba1a4",
          "sha256": "1af859c9a1bf4f59ca3ec1af077e8d65cef61f90960b3c792d3706243151a50c",
          "sha1": "1e780a3e07e1c83463ba9b7ba593e6abe2c22de7",
          "md5": "dbe6c1883ed9b13eee1c9b2b3c5d753f"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-watchosarm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-okio-watchosarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 4225,
          "sha512": "69283b909b2852f8174e5ef5ed5b288a478ce87980324c79bf800bc19b3aeaf113398ca22e4e8ac8299c5f0abbe4469d63b9f294c12e889659681763198e0e00",
          "sha256": "9728b0f43cfac52ea29b95eda581063d931d8c4e254585a5f010ec029e728697",
          "sha1": "01c2d3cd35733345c5c9b0a3d3d20f8de1fd4cd6",
          "md5": "afe1cf472b04904974de1ac0ad99e35e"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-watchosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-okio-watchosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "a1f81bbc4e6da344b8bfb7aea97f5a91562383b9206bd980b03ec64b5ec0cb0c1db3aa6a98e6243eba863119332f48b2c195c2056ad702178345760748032a84",
          "sha256": "0a01ec62cc11fff38f4de9a83e8d72ae9e5146654f002d5b8810b39fb498de4f",
          "sha1": "dff87f984c0790de9e901d6739d2d82565ce563b",
          "md5": "9b68ccdd0145fa511cee4255b6a4c65a"
        }
      ]
    }
  ]
}
