{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.8.0-SNAPSHOT/kotlinx-serialization-cbor-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-iossimulatorarm64-1.8.0-SNAPSHOT.klib",
          "size": 93052,
          "sha512": "a192aba4835d53fa74590fe178f2438df139cdf5cc789ccbed141703e15d0ef8c3f4d9c27f91125320bfcc033ff783eae555d01a13dc67a56a58a8ff40eb6ff2",
          "sha256": "fe1eb80574e8e4a0558fdcf0ca116deadc9b44aebea60e88c51fdca360250573",
          "sha1": "fd24c30740837c4a27924a7e6914d9c0e7c19511",
          "md5": "adcef3002d6e185973eb227be70555eb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-iossimulatorarm64-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-iossimulatorarm64-1.8.0-SNAPSHOT-sources.jar",
          "size": 24207,
          "sha512": "a6886a8a2a294780b6a715f4c13d11d584f4ae35beb80ff81849498069ea80560cd9cd29f478a30059de5b0dea9402ee5251d762c11c55ad8970c6022debabaf",
          "sha256": "02e95064eaebe90e7057626da1e41c2e5c710a8a28330df95dadff40e935c7ae",
          "sha1": "0733d6423ca1ee3ee0d2dd7ce117432bba6491ed",
          "md5": "d4b346b1845b2275ad3b2d6245f7cc24"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-iossimulatorarm64-1.8.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-cbor-iossimulatorarm64-1.8.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "faf3910c8d3f74b49cf8dcda837bc83953df3351fc1bd034a9e549418a9af79f1fa74784fa19f97b870eb67ee5cbf1b5929203444d84f43a4ea8b784c2d9e642",
          "sha256": "eb36adbfaae7f05cb4e62a1873f37b00790dd3c6345da96765db5a31650bc8e7",
          "sha1": "71037f01f111367fbb5130e4f887e5d68b85753a",
          "md5": "9d7bbd8b26ccda675b32da1d278c5da6"
        }
      ]
    }
  ]
}
