{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.3-SNAPSHOT/kotlinx-serialization-core-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-wasm-js-1.6.3-SNAPSHOT.klib",
          "url": "kotlinx-serialization-core-wasm-js-1.6.3-SNAPSHOT.klib",
          "size": 322304,
          "sha512": "30b0e08f7cba21a0f21f319aa5efcaf0dc1124654052c9f049ed03100a8b854eba8ff37b6e57cac8e6305508d30704c7644ba17269a2faf8efa70bf57e2efb09",
          "sha256": "5d6be72411425d55b16be99812c75db13ec1f5f8a93ece95af9a4e92da5bbe1c",
          "sha1": "e800d526ff5f31e4be87b11e03f8339d6c5a1e21",
          "md5": "97894ea39f57dfa51f2bb65922b07967"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-wasm-js-1.6.3-SNAPSHOT.klib",
          "url": "kotlinx-serialization-core-wasm-js-1.6.3-SNAPSHOT.klib",
          "size": 322304,
          "sha512": "30b0e08f7cba21a0f21f319aa5efcaf0dc1124654052c9f049ed03100a8b854eba8ff37b6e57cac8e6305508d30704c7644ba17269a2faf8efa70bf57e2efb09",
          "sha256": "5d6be72411425d55b16be99812c75db13ec1f5f8a93ece95af9a4e92da5bbe1c",
          "sha1": "e800d526ff5f31e4be87b11e03f8339d6c5a1e21",
          "md5": "97894ea39f57dfa51f2bb65922b07967"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-wasm-js-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-wasm-js-1.6.3-SNAPSHOT-sources.jar",
          "size": 98911,
          "sha512": "1264792f4f0898f1516880325f10546c85f2172531804549108b8dd18d45797fe31646e2b89c99290b8eeb1c9e97c446825614b34a9f2b5194263db6feb2d103",
          "sha256": "1e99e07b9fa6de8c41c62b5fa86166b32d923f7e49695a49e07972068aee1e97",
          "sha1": "6214704e6763ba9ca12410e0dc8e8313eb7dbd3f",
          "md5": "4392fd28ce87b832dc33bf0205d158aa"
        }
      ]
    }
  ]
}
