{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.6.0-SNAPSHOT/kotlinx-serialization-protobuf-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf.klib",
          "url": "kotlinx-serialization-protobuf-linuxarm64-1.6.0-SNAPSHOT.klib",
          "size": 120307,
          "sha512": "5320e25b97e2c2ccadf5fde3727cb78656b4dc245639e286c8ad4e090980f6c3fc4ec8cd064d4daaf835bd90c04a233a01555461c9944403d5b9cea273af6123",
          "sha256": "827e0b21d7ecf7470185b7101c4a19493656a44a94a9d0fa12f0fe2b49dbc36b",
          "sha1": "848ed73dfb649acece836529d9b68e167c3d68f9",
          "md5": "586a65ebdfe61a4c119f933e218253ae"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-linuxarm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-protobuf-linuxarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 28577,
          "sha512": "57f751425cedd7f474c3b7a7f9d0e57c449b7ace8b7cdad976e71480ac29bdd0708eed515511bb1ae44b634353d87c05166c410cfb86d121fb36331c599c421b",
          "sha256": "4b5c6ca97b4c62ee4e909132b80d1c9f487ec4ddd08b3a0014ac19e49cff28bd",
          "sha1": "096572e14d25cd2bca86b475346262d9be242407",
          "md5": "7cfed7b824307d147483c6794f150ea6"
        }
      ]
    }
  ]
}
