{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.6.0-SNAPSHOT/kotlinx-serialization-json-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-watchosarm64-1.6.0-SNAPSHOT.klib",
          "size": 247699,
          "sha512": "efbfb54f96fcd8fa7b8f8a31f0e73ea85d01e4b6cb4c381b0808233bd88fea4803398b0ea92dda141784e1f379ff1c7a5c3f43b2b8914ac1a6ac9b17ccdd401e",
          "sha256": "9a6e74a9ea87babc767d48608e72ee9b2fda92ac02dd582a746e8275c35cc151",
          "sha1": "20048ecb649051b285ca65d899b0aef415f5765a",
          "md5": "a313453ab0a23932e1fd6b6424b1a048"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-watchosarm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-watchosarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 73593,
          "sha512": "111f3c2443dbb3cb6537b5d9a92597b6c8b2bf9616833587dddfe2e80ccaf151d60b2201e7f535d22204a37cd56b0edde1a979eb6bd80b21f82bcfc03164f876",
          "sha256": "4b7dd8d46dd54a8f249db397553d290f77b5468477c849d25f8d6c4d52ca7e33",
          "sha1": "1d13131e61139f51287f933b0583331d3726e9e2",
          "md5": "bcc17f5e8e9f5b4f6e5d6dd5a816f90c"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-watchosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-watchosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ce76d42d0677bcd8cc662bb48b076c2c6dff304319458bec01d5e2519e19f1b090b77105295ed192c30d35c5d09901858fa6b7526502e7235af49ca6ad359cff",
          "sha256": "cc4aa7ae7b04d49a119a02c7a94d6ad1870a175d7f273424f3f479cc587f799c",
          "sha1": "d4e98ef0fe8b18b2ba02019bde6b8a2d97bc3fe9",
          "md5": "1a6db76e49923d721e8d6924036baf64"
        }
      ]
    }
  ]
}
