{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.7.1-SNAPSHOT/kotlinx-serialization-core-1.7.1-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-iosx64-1.7.1-SNAPSHOT.klib",
          "size": 325597,
          "sha512": "69b6680e8669f49d607c64dda0bbb93f8cb58b571e46aa3e9c6eae7d98c6a07aa7869bd387be8c1828ad9488171e4c12bc20e7841403a5de5a4264203933c8d2",
          "sha256": "d003ec5a7adb03badf35751a38c4e18755192889f33339e17e8bbe96e4905a0b",
          "sha1": "17cb3913d9747236d07cb66eea59275a79d6406d",
          "md5": "060261b676e23c941808d1d26964a535"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-iosx64-1.7.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-iosx64-1.7.1-SNAPSHOT-sources.jar",
          "size": 100345,
          "sha512": "869512f66d16d8a09099e39b29da203802cf7d1779f3b8fbea2a6069da6e3bad475d4b60bfd5553c8e546cb97222ee78d97d92a4cd96ca1af1b362901e122346",
          "sha256": "ab430185de994e88bf871f962f877b3e030ec35137beef0c2973f6dc0e14b55f",
          "sha1": "171da31ef477424df6c88cc77940d3fa10617b32",
          "md5": "afe36c66a49b324e693db0b6fa8612f7"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-iosx64-1.7.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-core-iosx64-1.7.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "26339b2329fdbf0fef15640747d5e468215e76947c1a2d4bd78c1172f7dd8c9545c47420f733bf1313e712f5018f110e6b73683113d32090b36f32c2cab91c68",
          "sha256": "a6f00746d51b8d72872c0466a799700a69f3aefd085a2987ae3d71d61442910f",
          "sha1": "4eca843d5145f755008a38e9e47b71de9c6b1daa",
          "md5": "17b3ebdead243c3f5e473de7de998a23"
        }
      ]
    }
  ]
}
