{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.0-SNAPSHOT/kotlinx-serialization-core-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-linuxx64-1.6.0-SNAPSHOT.klib",
          "size": 282805,
          "sha512": "3edc44b5aa95c6d3e985df3d43bc0e81b3b4625b2e90154583da582d0c20333832ab4291583e774757b02999f44db26437a653022ba5ac2161c4c15d25fc7a3c",
          "sha256": "52e47194b30a6a946b47725d41b77da9d1e0858e890c1e25ef6f8a8cf533ffb9",
          "sha1": "e934340e30f1ab290ca2dbad095ac7181da41c3d",
          "md5": "287db04ca6ff09fb57fb07fdd0cee5e1"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-linuxx64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-linuxx64-1.6.0-SNAPSHOT-sources.jar",
          "size": 98744,
          "sha512": "9b95c76e30bb8ecd501e72c05b4a7fecb351ed396654d6abc4944518c7a141faf89952cc3335e885c8eadb19a03e9e6abe5b7ee15d6c3be159307b42fc386cab",
          "sha256": "7b13559e42f741cfd0edfe3accc84610b2743d081de6ca2a68fdb65bd1cc4b95",
          "sha1": "4057cd6951920634815ee921e2ef63e2b9534fd1",
          "md5": "388393a5b3bfd3ade0a928af9435f9fa"
        }
      ]
    }
  ]
}
