{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.8.0-SNAPSHOT/kotlinx-serialization-core-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-linuxarm32hfp-1.8.0-SNAPSHOT.klib",
          "size": 325669,
          "sha512": "dd20c0cf170a448a51f8ae90ccf61a35e7576f437cd5feecfc1403239afd54d00be9f48e1b2f3344c2e7ea82d433a139ccd8ed49e7ac37e94d0dc0f0de6c654c",
          "sha256": "64dfb0ef8815369ee15e24ae638023e11c7851e0ecd6bfc2871727a98cbd8248",
          "sha1": "2daed46824fdec27cd52a09b88f0b87b8eb0c52a",
          "md5": "70e24b452356548d37cccdbe3491891f"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-linuxarm32hfp-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-linuxarm32hfp-1.8.0-SNAPSHOT-sources.jar",
          "size": 100345,
          "sha512": "869512f66d16d8a09099e39b29da203802cf7d1779f3b8fbea2a6069da6e3bad475d4b60bfd5553c8e546cb97222ee78d97d92a4cd96ca1af1b362901e122346",
          "sha256": "ab430185de994e88bf871f962f877b3e030ec35137beef0c2973f6dc0e14b55f",
          "sha1": "171da31ef477424df6c88cc77940d3fa10617b32",
          "md5": "afe36c66a49b324e693db0b6fa8612f7"
        }
      ]
    }
  ]
}
