{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.0-SNAPSHOT/kotlinx-serialization-core-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-androidnativex86-1.6.0-SNAPSHOT.klib",
          "size": 282822,
          "sha512": "a857119207d0c98543fe63b03a6c5ee8b3f738f718bc7609a7d10c497a2c9c597f0ebcd93f9f42d1260215653e8a8c3b88f90933d234b14c3f59240691cda857",
          "sha256": "5fcb6eb92159c8e44c227939084f14529d75ddc2836457294810d6fe96dedbcb",
          "sha1": "acb49f5f954373340878994abcaaecb47a8727a0",
          "md5": "fb1c40687aaef555878752bbb73c9a0f"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-androidnativex86-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-androidnativex86-1.6.0-SNAPSHOT-sources.jar",
          "size": 98744,
          "sha512": "9b95c76e30bb8ecd501e72c05b4a7fecb351ed396654d6abc4944518c7a141faf89952cc3335e885c8eadb19a03e9e6abe5b7ee15d6c3be159307b42fc386cab",
          "sha256": "7b13559e42f741cfd0edfe3accc84610b2743d081de6ca2a68fdb65bd1cc4b95",
          "sha1": "4057cd6951920634815ee921e2ef63e2b9534fd1",
          "md5": "388393a5b3bfd3ade0a928af9435f9fa"
        }
      ]
    }
  ]
}
