{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.7.2-SNAPSHOT/kotlinx-serialization-protobuf-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-wasi",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-wasm-wasi-1.7.2-SNAPSHOT.klib",
          "url": "kotlinx-serialization-protobuf-wasm-wasi-1.7.2-SNAPSHOT.klib",
          "size": 147912,
          "sha512": "fda3d01c3a5b7065ca11a9e89d704b6627be4183ae9346d5d62968f71fb2ad959bec87caa89949761a0e89be59ab385e9c25c55b4da67a83a1ec75939a2b5541",
          "sha256": "9dca54bce48ae086f70321eff6cd5555425ebc7c54dd75efe804e520b3e523ba",
          "sha1": "6c38a2964cee5aab208b07a2be6c85a161214207",
          "md5": "ac8e8b2187cca695e1fadae9fb3831b1"
        }
      ]
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-wasi",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-wasm-wasi-1.7.2-SNAPSHOT.klib",
          "url": "kotlinx-serialization-protobuf-wasm-wasi-1.7.2-SNAPSHOT.klib",
          "size": 147912,
          "sha512": "fda3d01c3a5b7065ca11a9e89d704b6627be4183ae9346d5d62968f71fb2ad959bec87caa89949761a0e89be59ab385e9c25c55b4da67a83a1ec75939a2b5541",
          "sha256": "9dca54bce48ae086f70321eff6cd5555425ebc7c54dd75efe804e520b3e523ba",
          "sha1": "6c38a2964cee5aab208b07a2be6c85a161214207",
          "md5": "ac8e8b2187cca695e1fadae9fb3831b1"
        }
      ]
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-wasm-wasi-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-protobuf-wasm-wasi-1.7.2-SNAPSHOT-sources.jar",
          "size": 32119,
          "sha512": "98054804dc8749a112eb13938e02764ea056eaa2f847b40587438bb48e81e82d3dc567a351e539fe6738bc3580eb92a69f28148ae906c9f3e97318d908f0207f",
          "sha256": "adf0cfb17060e268e803b4ae360d620bac56ba6466d2c0cacdec5f24fbdcc8d9",
          "sha1": "53e0286c92b60e556ea70fdf3d1082bc3a0e6649",
          "md5": "ce1e824ed4bd12f764c10614eb14bb82"
        }
      ]
    }
  ]
}
