{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.6.0-SNAPSHOT/kotlinx-serialization-properties-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-iossimulatorarm64-1.6.0-SNAPSHOT.klib",
          "size": 19695,
          "sha512": "322884ee3ec84a78f75454c64765df299666e4761d4a10e10755f45fb4df6527dc3306e8287e0fafbba40c42a0f1639299b123117cce5d09565f642c70468bc0",
          "sha256": "04b954dd78acea7beaa6aec384f5d6f661719da352571d3ee8cd3cf6339a9b64",
          "sha1": "9742b5703ce8a87b2376c48ee5cb524be3235f5a",
          "md5": "b69b4f99c6022851895ea66a8788bf76"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-iossimulatorarm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-iossimulatorarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 3766,
          "sha512": "a5bd31251a9c5283b9ee19bfccdab80225e5a9308307d07b0ac81d9950c9c08123c2dab9a208588943b7e7b08c3c9214017a378bc7c89fc0806edba717461b90",
          "sha256": "6271ba0299d4710db9c9bb890166eb8011dfe605ac60bb35043106e60971e815",
          "sha1": "1453a245d2574f74898d4f20b6f97b889b303660",
          "md5": "632184f558a1323015aa2d74c57bc53e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-iossimulatorarm64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-iossimulatorarm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "80545b0792a4d401b4d9d3fa777f5aaaf2a5cdc82b6226862e3e002bfb0e43bf78b64ea85d9bbdd09e57318c8fb291c9dcf84417d639f99d761c7606859b0134",
          "sha256": "c5f2b51b6fee3ae708110ae52d67aac99283e9afd866af2b12c9d2cb1f969263",
          "sha1": "2cb5477ebf290137c7c96095e4043953210a21c4",
          "md5": "17e8a6108ae9dc18ae4de61964928261"
        }
      ]
    }
  ]
}
