{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.8.0-SNAPSHOT/kotlinx-serialization-protobuf-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf.klib",
          "url": "kotlinx-serialization-protobuf-macosarm64-1.8.0-SNAPSHOT.klib",
          "size": 149339,
          "sha512": "17cc174166edf8f572716f7a15d1648220393e49aa9717917f81010e4ec3800dbf16420b1cf7713bc963abbc1191e9735fc59ba6dee76aa8ab10c3db558493c9",
          "sha256": "8f943650a8c7d3670c944a91ede95ccbb0aeb677c18a23f44e5a55ed5120f9bb",
          "sha1": "1d05529af9a9b5f997df235b0ea0229847303786",
          "md5": "42153bd9659faca395db73111188f317"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-macosarm64-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-protobuf-macosarm64-1.8.0-SNAPSHOT-sources.jar",
          "size": 32143,
          "sha512": "5d0acd6f288db1c9f96e6c6537a67da702a13c5951afeb85edc7aaa92a0ca4519ae4231645b5694accb5312190b8a6974a56a09e4ab4c7998b0cd0b9a9b65cae",
          "sha256": "1c0490bd839a1b04c1f78a80e1dc9912ec33bc933ca1ea0e55d2ca00f9922d6e",
          "sha1": "25f8c3f1ef7a22eff21443d76cb39674c0a2687d",
          "md5": "4adfe75163bb4373e0d30d84bf5230a8"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-macosarm64-1.8.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-protobuf-macosarm64-1.8.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b7c9508285af742741d4b2469c8aa7fe6c5f0e4d2423361698e23957f2a4da31d5ab1a2c4251b0ea3477b1fa851a87049a5a8fedba6a3f0c050503b1c530cd95",
          "sha256": "cc455d78c7bc20c9fd882b7f16a28fe07de287262a7e592f7114f377cb7bded5",
          "sha1": "4f16a94492207cd9c7ca137bf37c5ac0ed12c1de",
          "md5": "0a52f6440a82603a04c9dcf884b7fca6"
        }
      ]
    }
  ]
}
