{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.8.0-SNAPSHOT/kotlinx-serialization-json-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-wasm-js-1.8.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-wasm-js-1.8.0-SNAPSHOT.klib",
          "size": 300637,
          "sha512": "a11e878e7a6b95addeb7c24f47690b423b8fee570e3f630b1e30911ebdd1040ebcb4ba0d668990fc6679f74dd957acfa7602c0f9ecfeeef66b47cd134b5498fa",
          "sha256": "98e76e929c60d50e2f950d3793b6ebeee7d8eafee01c400ea988fcfe46776f28",
          "sha1": "199c3fff5e7fa7030dca184436d3b74ac5fe190e",
          "md5": "166ca92bc17cc3c214c304460faf22c2"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-wasm-js-1.8.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-wasm-js-1.8.0-SNAPSHOT.klib",
          "size": 300637,
          "sha512": "a11e878e7a6b95addeb7c24f47690b423b8fee570e3f630b1e30911ebdd1040ebcb4ba0d668990fc6679f74dd957acfa7602c0f9ecfeeef66b47cd134b5498fa",
          "sha256": "98e76e929c60d50e2f950d3793b6ebeee7d8eafee01c400ea988fcfe46776f28",
          "sha1": "199c3fff5e7fa7030dca184436d3b74ac5fe190e",
          "md5": "166ca92bc17cc3c214c304460faf22c2"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-wasm-js-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-wasm-js-1.8.0-SNAPSHOT-sources.jar",
          "size": 81430,
          "sha512": "be88415b06b3b6a99129c2520e09bb62124efa621c53616c4898b107a6d7000115a12d3cf97c7200195c5a768883874598474b3f9787d72b7a8c78730fa4bfd3",
          "sha256": "24e6318e8858e901e3cf9f59b759113f9179844a24f5c7cbbdd175272d1a0dad",
          "sha1": "ca5238542cbd993a3bb010c5514b4f34649c6d61",
          "md5": "66d406749431b89a4fbe1da88e6477a3"
        }
      ]
    }
  ]
}
