{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.6.3-SNAPSHOT/kotlinx-serialization-properties-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-tvosx64-1.6.3-SNAPSHOT.klib",
          "size": 21198,
          "sha512": "c50f4fcb9a9d42150e63108009cfa16c0acf1ce98e0b989ceef7a19dbb04fc0614b36e2e700efda5f72a2c01c2710e51ff16ff155ea9b866c7edae70e123fbd8",
          "sha256": "dd161c0171102dd7721d4680ea9949c3bbee67c9dfd8e55ceb9a41d997729df8",
          "sha1": "54b67f503b5590abf044dcfd2b8926349dfb80eb",
          "md5": "10e3f75b043516397af714891af6ec3f"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-tvosx64-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-tvosx64-1.6.3-SNAPSHOT-sources.jar",
          "size": 3766,
          "sha512": "a5bd31251a9c5283b9ee19bfccdab80225e5a9308307d07b0ac81d9950c9c08123c2dab9a208588943b7e7b08c3c9214017a378bc7c89fc0806edba717461b90",
          "sha256": "6271ba0299d4710db9c9bb890166eb8011dfe605ac60bb35043106e60971e815",
          "sha1": "1453a245d2574f74898d4f20b6f97b889b303660",
          "md5": "632184f558a1323015aa2d74c57bc53e"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-tvosx64-1.6.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-tvosx64-1.6.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7baaaeea55709e9b10f7b59fcb805de73a11f53873ecdb6e8c7374b2049c84d656a388fe9bdc52a25e61baf7ff299f51e2d14b22411e91fe0d3bf2c21524a1fc",
          "sha256": "4f78f87d402a967d33814fb7486d474ddbbdad6a04b604f3ed986aa7c1732b8d",
          "sha1": "69cad9c38a3b9156e564de92c78fbc24e961eda7",
          "md5": "7c683507a01af2b914da98078e6883a7"
        }
      ]
    }
  ]
}
