{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.6.0-SNAPSHOT/kotlinx-serialization-cbor-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-iosx64-1.6.0-SNAPSHOT.klib",
          "size": 86696,
          "sha512": "094326257f235bd740a76afc75724c11df4a17d4c2ac2afc5a8d07e2448284d76a17c47537d7de2dbe8ad47da395324010b732c4a29e9aedc10a3e3380e9a990",
          "sha256": "6b5c85bbe15edfdc1524c9d3124ec35c9c224766b4b80add274d971a9bbc1376",
          "sha1": "096d240fdde945a25802c26929cef09bdc1804e7",
          "md5": "3d2fea8fc8286bed7834b47ca52307e2"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-iosx64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-iosx64-1.6.0-SNAPSHOT-sources.jar",
          "size": 16435,
          "sha512": "826f0a085a07e9b8ae76dbb73b534140539ec5829964a46dad78baad71ed146d517b1a41e7c2221b66c79d41e75380236179f8050b9b611583bc52540200c3b5",
          "sha256": "bee65713d03f075601ee5ecc9b7605c684bc6c12cc77caaff28786a0724ece25",
          "sha1": "9238164915194e2d68f4fbc95967123362a232ac",
          "md5": "1914c2244541c5af3415b21d581ebc55"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-iosx64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-cbor-iosx64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "88d969e936ccd9c5505298774ad7a6fcfc37ef1154d68aa9edb9d282677ccf333fcefd6ced2e3b80597b60e2a75429ef3b592819d8e11b47ff59de3a7352f97f",
          "sha256": "e4c9e934dc64fef6858eb56c3a82501fb455e2fb2bc070c0b55289f93b698dd7",
          "sha1": "b9644849a1ee0d675e6479d8fb70194e4ec9beb2",
          "md5": "fa9ee9622943969da32d516be3bf2165"
        }
      ]
    }
  ]
}
