{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.0-SNAPSHOT/kotlinx-serialization-core-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-watchosarm32-1.6.0-SNAPSHOT.klib",
          "size": 282840,
          "sha512": "a21049212e40ebde62e5d1e49a98df813bb1de04f30d85b83e1986d1e9359f4e08cd272b78d898f914d7d10002c18cf0f85b894155d54a830e67c830c5c64ea1",
          "sha256": "c0324c715aaa479f5e7e9605848124d768eda23076d04f07be61b08d5912da94",
          "sha1": "a4a7c1cc44bda6013dcebaaf4db1323749d8783d",
          "md5": "19f3c38a93a515b65182b5159798d243"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-watchosarm32-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-watchosarm32-1.6.0-SNAPSHOT-sources.jar",
          "size": 98744,
          "sha512": "9b95c76e30bb8ecd501e72c05b4a7fecb351ed396654d6abc4944518c7a141faf89952cc3335e885c8eadb19a03e9e6abe5b7ee15d6c3be159307b42fc386cab",
          "sha256": "7b13559e42f741cfd0edfe3accc84610b2743d081de6ca2a68fdb65bd1cc4b95",
          "sha1": "4057cd6951920634815ee921e2ef63e2b9534fd1",
          "md5": "388393a5b3bfd3ade0a928af9435f9fa"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-watchosarm32-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-core-watchosarm32-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0e3c8b295c52cfee216f47787a07961886e504206a35492befaa6dcbf6c251b89487ea85f01faffe1f602fa55856e17a7f3fb00e9530d2b98bdd7dc6be0d6df3",
          "sha256": "3bbbaf3758781c9862a5857e417c0b302f69475c4d52a479b8ddaece0456ebd8",
          "sha1": "b4442c782142c24883c07c38a2455346deaaf368",
          "md5": "20597a311497dec1cdab28fa8fc08f69"
        }
      ]
    }
  ]
}
