{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.6.0-SNAPSHOT/kotlinx-serialization-json-okio-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio.klib",
          "url": "kotlinx-serialization-json-okio-iosarm64-1.6.0-SNAPSHOT.klib",
          "size": 15710,
          "sha512": "a38a761a7f49a85340c913c841414cfb96595c90357dc85d2ad7d80820d67b2066a607155e834b5a9d0cd2e61acc6b8895f2d0dc95726e56e7006756f00db6c8",
          "sha256": "325ae632ebffcae146f17b28f573393195a1312656678cd092309ff6c45da186",
          "sha1": "e95d6d3cfe691976528d5335f654701fc5b26af5",
          "md5": "d3979bd4135e792320ff9ae49e7466f0"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-iosarm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-okio-iosarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 4225,
          "sha512": "69283b909b2852f8174e5ef5ed5b288a478ce87980324c79bf800bc19b3aeaf113398ca22e4e8ac8299c5f0abbe4469d63b9f294c12e889659681763198e0e00",
          "sha256": "9728b0f43cfac52ea29b95eda581063d931d8c4e254585a5f010ec029e728697",
          "sha1": "01c2d3cd35733345c5c9b0a3d3d20f8de1fd4cd6",
          "md5": "afe1cf472b04904974de1ac0ad99e35e"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-iosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-okio-iosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0d74150d1da56d65cd68bdb75ad3cdd740eac54ae3cfb9caa143b27c4bf43440dc58a6163e923ce4207b34abbef2f1a7036faeea567859827532448fb8828b92",
          "sha256": "21f152c6a18a6d642b1ee9a940176a1006bca5583255df1423a373d233b97e7e",
          "sha1": "81736b9639dd0662b7918789ac12f875bcb964e7",
          "md5": "de98c1ac3a4b2dab47a3cd8efbb30bd4"
        }
      ]
    }
  ]
}
