{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.7.2-SNAPSHOT/kotlinx-serialization-json-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-wasm-js-1.7.2-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-wasm-js-1.7.2-SNAPSHOT.klib",
          "size": 294994,
          "sha512": "fc6c8fb3cc29b7c4efd766654dbda5da4b1a8dec7fb7929509736ef9626186d46327df4d846c90e88b8804db23d60d76f76f3640b6f1aafb8e90aae9fddcc49f",
          "sha256": "0a4c3413eefca3824b80b63d8bb846d881f65c806bbdf1c6b5c26beef64b0b13",
          "sha1": "0e06c6f77b84a91217a4a5899be1a0a1fdf8ec6f",
          "md5": "1cc1546e3b696196f841bb35fd460f87"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-wasm-js-1.7.2-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-wasm-js-1.7.2-SNAPSHOT.klib",
          "size": 294994,
          "sha512": "fc6c8fb3cc29b7c4efd766654dbda5da4b1a8dec7fb7929509736ef9626186d46327df4d846c90e88b8804db23d60d76f76f3640b6f1aafb8e90aae9fddcc49f",
          "sha256": "0a4c3413eefca3824b80b63d8bb846d881f65c806bbdf1c6b5c26beef64b0b13",
          "sha1": "0e06c6f77b84a91217a4a5899be1a0a1fdf8ec6f",
          "md5": "1cc1546e3b696196f841bb35fd460f87"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-wasm-js-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-wasm-js-1.7.2-SNAPSHOT-sources.jar",
          "size": 80366,
          "sha512": "cf91dbff5b6a7b7c72d5b86a9912bf8055d7a25740aefe2a53d61d184dc7e9e07a92ada9b78abb3c00cc5a03ab8f7f7967fe2fac87958d2058e2135008a6d12b",
          "sha256": "2fe8da6a432f6477507cecc209c9006b935b1f6b5fd185b44355eaf882cc8d80",
          "sha1": "ddd44399aa9a3d9ba1725c5bc653c1319923c8fe",
          "md5": "508b9f56b66088c6ecfea80696d97211"
        }
      ]
    }
  ]
}
