{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.7.1-SNAPSHOT/kotlinx-serialization-protobuf-1.7.1-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf.klib",
          "url": "kotlinx-serialization-protobuf-iossimulatorarm64-1.7.1-SNAPSHOT.klib",
          "size": 149407,
          "sha512": "0d408375ebb794da94c29e2819ca6a6bb4202ee02fa316c58f291c27897fffeb6efa1871f589942f39cf17e2817667ca0e4dcee227165d8ccbab190c4107d6fa",
          "sha256": "bbb12745f71132c5018a5e3dc42332b596bbeb8e99b9204d0102eefdc36bc73f",
          "sha1": "f44c1f05b7b989fec3898e4998ebdaa081a57d43",
          "md5": "0afa462b65c06aedd191c1c0d228e578"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-iossimulatorarm64-1.7.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-protobuf-iossimulatorarm64-1.7.1-SNAPSHOT-sources.jar",
          "size": 32143,
          "sha512": "5d0acd6f288db1c9f96e6c6537a67da702a13c5951afeb85edc7aaa92a0ca4519ae4231645b5694accb5312190b8a6974a56a09e4ab4c7998b0cd0b9a9b65cae",
          "sha256": "1c0490bd839a1b04c1f78a80e1dc9912ec33bc933ca1ea0e55d2ca00f9922d6e",
          "sha1": "25f8c3f1ef7a22eff21443d76cb39674c0a2687d",
          "md5": "4adfe75163bb4373e0d30d84bf5230a8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-iossimulatorarm64-1.7.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-protobuf-iossimulatorarm64-1.7.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0f36a48ec71a93f9d0a40fdb3f59501e21c9f6846b59a6600ba6f13dd05733d6c9e7f2b94c9f0260d205f44a96261dab50a37b8ad9329449a4d08ff3edbc40ea",
          "sha256": "b93979ed368a06b03fc76169bfc54fedb7afeac5cca5c1c1873c520c40551030",
          "sha1": "067125d18c1800af54c3257dce0c11049ef85ea3",
          "md5": "315f980cb209b05c7a9162a2edd68216"
        }
      ]
    }
  ]
}
