{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.7.2-SNAPSHOT/kotlinx-serialization-cbor-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-wasm-js-1.7.2-SNAPSHOT.klib",
          "url": "kotlinx-serialization-cbor-wasm-js-1.7.2-SNAPSHOT.klib",
          "size": 92546,
          "sha512": "b0093d9118aa64efe6d4292de84ec688cbd98d8db98ac33bb272158994a25bfde15f41240bd9fd7649c390a4af482ea9702a3ec6dd88078356ffb5652b0eb2c1",
          "sha256": "81244c73ad4fdc891f73974aef64dba8997f6a8eb25e4cb5ee726002c11f7157",
          "sha1": "ac5e94352d33d31c221a5b669749aef277f7f668",
          "md5": "4ab1d308ad2815e4e0a94269de296ad7"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-wasm-js-1.7.2-SNAPSHOT.klib",
          "url": "kotlinx-serialization-cbor-wasm-js-1.7.2-SNAPSHOT.klib",
          "size": 92546,
          "sha512": "b0093d9118aa64efe6d4292de84ec688cbd98d8db98ac33bb272158994a25bfde15f41240bd9fd7649c390a4af482ea9702a3ec6dd88078356ffb5652b0eb2c1",
          "sha256": "81244c73ad4fdc891f73974aef64dba8997f6a8eb25e4cb5ee726002c11f7157",
          "sha1": "ac5e94352d33d31c221a5b669749aef277f7f668",
          "md5": "4ab1d308ad2815e4e0a94269de296ad7"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-wasm-js-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-wasm-js-1.7.2-SNAPSHOT-sources.jar",
          "size": 19425,
          "sha512": "ffb1f6d8a03d975913e47a3b3294ac160b40497e9dc09c1851d8153136829678891b8f25e853f026c5bba13bd1cf683d32bb856d2cb5cfcc910d9fa59fb59558",
          "sha256": "c137c04407f379f0a1bfc3b98b5a5aa8b7dfbce5017e369b6613340b58a49e50",
          "sha1": "c0245c967deffe9275fd9240d005f1788f7597d4",
          "md5": "d2ffde2434a3f49dbe0c66fcd21a4768"
        }
      ]
    }
  ]
}
