{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-hocon",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.6.3-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.6.3-SNAPSHOT.jar",
          "size": 65671,
          "sha512": "56abed7c63bb9ef1b629513673be40621b7f313ddb833d3e008344742ba7c9074d0c1eb38b64a37addeefe6c8e165d6e19868f8e49c19d18be2d305a87855f3f",
          "sha256": "0db1e01e5971e24e8ed6b01ed5883df5d7db7396f21cc3189d455c0c1bbbe69f",
          "sha1": "4d793e45cf120bd7671fb0d3aef7176bf06a3cea",
          "md5": "7b7197017b1fc1b3d86b05782184137a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.6.3-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.6.3-SNAPSHOT.jar",
          "size": 65671,
          "sha512": "56abed7c63bb9ef1b629513673be40621b7f313ddb833d3e008344742ba7c9074d0c1eb38b64a37addeefe6c8e165d6e19868f8e49c19d18be2d305a87855f3f",
          "sha256": "0db1e01e5971e24e8ed6b01ed5883df5d7db7396f21cc3189d455c0c1bbbe69f",
          "sha1": "4d793e45cf120bd7671fb0d3aef7176bf06a3cea",
          "md5": "7b7197017b1fc1b3d86b05782184137a"
        }
      ]
    }
  ]
}
