{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.3-SNAPSHOT/kotlinx-serialization-core-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-androidnativearm64-1.6.3-SNAPSHOT.klib",
          "size": 306208,
          "sha512": "902415b61165d1e817168dede8a87e453faf5557b5c24b50214c07e4cbb74da1efc6627599d466dedf1a632d19af1dca6b904207c067bd6c256ba2fcf1d604af",
          "sha256": "f42289905a492a2c8971e7cce094d784c4df63e53b323344ab082ce6aab61d66",
          "sha1": "85e0c4d2275a1fdb03d770167901fd384306743e",
          "md5": "8b6c5ad233bb53087dcf7fa43c263cc0"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-androidnativearm64-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-androidnativearm64-1.6.3-SNAPSHOT-sources.jar",
          "size": 99052,
          "sha512": "7281b9edb91185f348d47a201c02d68a41fc1cf0d18dfd62f735cd6de905e37b83ca2df5091291373bab770d82bfba1792b39fb916ec0755a1905c39846f2e3b",
          "sha256": "fc5200b131b5f7f9734678d0a72d7b56e9b6989e6c1314774dd03ba23146b4ee",
          "sha1": "492370b6adab3a1c2c58f169b2f9de19292eae8c",
          "md5": "fa2e3374bde4370cb43f57b31984131b"
        }
      ]
    }
  ]
}
