{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.7.1-SNAPSHOT/kotlinx-serialization-core-1.7.1-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.7.1-SNAPSHOT.jar",
          "url": "kotlinx-serialization-core-jvm-1.7.1-SNAPSHOT.jar",
          "size": 388320,
          "sha512": "14391f7864fe6c79f64884aadcfea104ca2c8f3b23fd7d5a2c3e3510c3281cfb73062536275e6f7bf663b5b139cfe76d7a6060f68ee2fb80ad4d7399833b4f1f",
          "sha256": "59f321840cd66d06e968cb41725260911debf6622c0e2ff92cac3e88cd401e19",
          "sha1": "e66d0cff4040c52a3f748bc36c915ff2fa48c533",
          "md5": "d4150ba2579b606a881597ec83420a34"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.7.1-SNAPSHOT.jar",
          "url": "kotlinx-serialization-core-jvm-1.7.1-SNAPSHOT.jar",
          "size": 388320,
          "sha512": "14391f7864fe6c79f64884aadcfea104ca2c8f3b23fd7d5a2c3e3510c3281cfb73062536275e6f7bf663b5b139cfe76d7a6060f68ee2fb80ad4d7399833b4f1f",
          "sha256": "59f321840cd66d06e968cb41725260911debf6622c0e2ff92cac3e88cd401e19",
          "sha1": "e66d0cff4040c52a3f748bc36c915ff2fa48c533",
          "md5": "d4150ba2579b606a881597ec83420a34"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.7.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-jvm-1.7.1-SNAPSHOT-sources.jar",
          "size": 105989,
          "sha512": "60539211a58c2d2a81faf7d042b2123eca2ecde493dead319e928481d2fbe90b55977480b1f2d67f90944513b8a0cf1977f45ae820ba2ae2e212b81005e13256",
          "sha256": "6707b350a9c9f875c0a00fee2cbe915e1a6371b0064265a7f5d2ec5fe89134d5",
          "sha1": "bfb5874824e00b6391489a26c83ff48a6f129b97",
          "md5": "0eebc7bde5469ad7487acf3909b8d874"
        }
      ]
    }
  ]
}
