{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.7.2-SNAPSHOT/kotlinx-serialization-core-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-tvossimulatorarm64-1.7.2-SNAPSHOT.klib",
          "size": 325711,
          "sha512": "61c144868ee088f305e4bf88404c7326c8046dbe394c6939a052d4388f282fb0afc3d1675ce1da54c7e5cd97244f6eb63db21351497d5ed7e9ba2b0a28cb7e3c",
          "sha256": "af00bdd880dd464e9f69f41139a550705bc48e02e477f19634dd132ed03b2184",
          "sha1": "eaab7e81c8ac6ce47dd5dca1243185a8df438399",
          "md5": "79bffb3f11f7c49b13446aaad00598f2"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-tvossimulatorarm64-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-tvossimulatorarm64-1.7.2-SNAPSHOT-sources.jar",
          "size": 100345,
          "sha512": "869512f66d16d8a09099e39b29da203802cf7d1779f3b8fbea2a6069da6e3bad475d4b60bfd5553c8e546cb97222ee78d97d92a4cd96ca1af1b362901e122346",
          "sha256": "ab430185de994e88bf871f962f877b3e030ec35137beef0c2973f6dc0e14b55f",
          "sha1": "171da31ef477424df6c88cc77940d3fa10617b32",
          "md5": "afe36c66a49b324e693db0b6fa8612f7"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-tvossimulatorarm64-1.7.2-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-core-tvossimulatorarm64-1.7.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ff69ac4747620132946bd698c74ca18230293932b125ff5dc38b3242714662f59cbfd19f99a1fe371f1e55a6f63372ff7842830507a14af78254619da28e05d2",
          "sha256": "97cd4cb084b062cb06206222a27e29bcd104258a9f9c3c897db5dfb126c8ded3",
          "sha1": "9870cd76532a27d90e759ce97bdc3800ac85f24a",
          "md5": "0d8247f38622dea4247aee5d420a43e0"
        }
      ]
    }
  ]
}
