{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.6.3-SNAPSHOT/kotlinx-serialization-json-okio-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio.klib",
          "url": "kotlinx-serialization-json-okio-linuxarm64-1.6.3-SNAPSHOT.klib",
          "size": 18245,
          "sha512": "d171949b3ef32dee2bb89390e2d96f4573c8d7a3e68479f7f82fb28468556ce64330a22ae0a693b230b5fe663ada96668aa94fdf1292c1d12746d7b274f39160",
          "sha256": "8439b876af0080b891e166709daed6174974f64e165dbc8fcfba5daf8f22f564",
          "sha1": "e25c2afdc43a8ebcfcf691a43117ae13436de13b",
          "md5": "c8ff8d485bc34e71dc6e3877f214d93c"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-linuxarm64-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-okio-linuxarm64-1.6.3-SNAPSHOT-sources.jar",
          "size": 4356,
          "sha512": "8a5eb4ef2bfba1b6b2b8bfa693f2d5060024ac3fddaa2cfc983642bb46a2e2bfaf060124fd36c8d78cb08b8d11ace39e4a044d0a82d952c051d7a66b3aaf16d1",
          "sha256": "f0593c18eb4f8ec337ce775fe7e2a0febbcee04f26afef935a69f3347d2c34a6",
          "sha1": "e6eb7473a38235959c4c5f2ab7921695b21f5c21",
          "md5": "1df8c3f6fa85629d9a5f920f46753a4d"
        }
      ]
    }
  ]
}
