{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.7.1-SNAPSHOT/kotlinx-serialization-cbor-1.7.1-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-tvosarm64-1.7.1-SNAPSHOT.klib",
          "size": 94815,
          "sha512": "baa0c02c0819c63ad06605586826316154deb6b3b40b719ac021bfddbf4dc3772d4471a2f7184bbfb3e591279e7c6698c44de8f185152543dae67cc437aa53b6",
          "sha256": "9826145b5b063275afb903555b97dcee15536441d39d82c6e9f1d19a0066a209",
          "sha1": "b5aa4844cc3965a815a3bb1a827af901fb6d5304",
          "md5": "7a3aa5d9debc498de79151d28b8dd813"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-tvosarm64-1.7.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-tvosarm64-1.7.1-SNAPSHOT-sources.jar",
          "size": 18897,
          "sha512": "a63dc917312b163f69d490eda6a6ccc95d491217b78b5784ea16477a1c7e049075af99797b7b74d6a5b28ba6a33e8fa05fbe4519d0e2a80b545eb7b76b21db2d",
          "sha256": "75bfaa21ec985c5dafbd48e87d30552ff3bf8d013e8c032bbf05bc88494cc856",
          "sha1": "183f81c6706540efe678229def6e145c2e0e396c",
          "md5": "1783d809cb809120d7b368a73df60961"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-tvosarm64-1.7.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-cbor-tvosarm64-1.7.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7a418b2fab8262bb302d22a8acb435fc59b5870621eb03c26542a3fd58112cb83d1b8baea4d28b44578c4358be16c256d76ab1244f277e18768413f52c6b88f3",
          "sha256": "4fb900323e5b8573af42e1f7ace43727779120f7a1fba4726b5af15b198f8943",
          "sha1": "c2c1e969cc5136995f79fb261f94a8c2e6d5530f",
          "md5": "b1b504ff3fba714124a8815673b4e62f"
        }
      ]
    }
  ]
}
