{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.8.0-SNAPSHOT/kotlinx-serialization-properties-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-tvosarm64-1.8.0-SNAPSHOT.klib",
          "size": 18770,
          "sha512": "379de169497937212823f4613f5d5e7f82f985a099b83226203113b5ed029d9f7fd292c4db57a3b423607b7abd6a0626939fddd23a1b2c1d10dfca1d60d4450d",
          "sha256": "66b91889ca9536c6915d61999a4393f7d55b037c6a9a02af162bd17aef9c38d6",
          "sha1": "bcfb6c8267812abacc91d06222665eca2fa1e5d6",
          "md5": "adf7b8aed2ca98843bcc23857fce1a2f"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-tvosarm64-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-tvosarm64-1.8.0-SNAPSHOT-sources.jar",
          "size": 3692,
          "sha512": "59ddd7439185a552035f7e09e3bad84e212673bb218ba42b003ad79be221ffa9a231f4738de5eeb9a7a9955fcb9869ddd72958896104f6c7654afda9dfa4eecd",
          "sha256": "f0edaa0a99e24d8a9953ea734b3eb78428ec949dd568e1eb7125e604e6714831",
          "sha1": "0f16141a0888abd29bba2d9cd82aa4230daa7275",
          "md5": "1f1a044c083221b07767f71927933221"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-tvosarm64-1.8.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-tvosarm64-1.8.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ac9c553f9cad298560cef8cf0482fb1f6f06d2badd2bda44691c83f4a7987a69ee86f2c97c9ad257451cb9e5e36f7e4efa6cdf511d45ac3a2443209ad742dd74",
          "sha256": "eb6e6e652fba9ed58683ea09de8119bf4cef614ecbedaa66d3e84cb16065f522",
          "sha1": "ba1d3588e364e60eb977b9d05984831bd4b25b8f",
          "md5": "370607e2a2bbe6bfee762a4ee65f3d9c"
        }
      ]
    }
  ]
}
