{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.6.3-SNAPSHOT/kotlinx-serialization-json-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-iosx64-1.6.3-SNAPSHOT.klib",
          "size": 272602,
          "sha512": "684497a85ea88fed067b9d43d899ed42dd587b84890fb9ff475eeb8725a3737aa3301bc57974bca9f471ce2c1f3dbc588cb5a208912c4540a556220d4ce2d3df",
          "sha256": "94c1af1ad54b4ed831194119ccf671605b1016d22983994ff2eddf874e98cb52",
          "sha1": "5a964a5bbe2cbf2fa393974139a32df1db510c5c",
          "md5": "8e2e4aa3178b34868799b61dfc13a8b1"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-iosx64-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-iosx64-1.6.3-SNAPSHOT-sources.jar",
          "size": 75475,
          "sha512": "612d68f19e08ba97da2af29681762e44a75715696c2f7c701e5827e24ae79cfcff41806ae10c6495987ff18b3f858b7ac16fffe012e402d60161b7eac4537f77",
          "sha256": "1d6191146cc5fca60a4b4e7dffd6498fe06eada634f20649a58eb2539fc1133c",
          "sha1": "fafaa45e226942a5c14bb7a4ab117ee231fdd365",
          "md5": "918557f577b85f53cf8e9eaef52890c3"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-iosx64-1.6.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-iosx64-1.6.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ceadc8d9c6d80323fa478159ed8b5a0ee8af3f6e7a72a926cca0c94636041eec77b6b3e1939932b89e5b1049812a09431c15cbb617c24e7a2b1058d79e6c240d",
          "sha256": "853f3774c24723108f5bbd93d98fc5fc1a829420c58cc148e154b8ac9bedb188",
          "sha1": "99c2da363668d1df5dd6e070675b13b7c2c494fa",
          "md5": "0c7e1f77acb632db6d3f328450a164c9"
        }
      ]
    }
  ]
}
