{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.0-SNAPSHOT/kotlinx-serialization-core-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-js-1.6.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-core-js-1.6.0-SNAPSHOT.klib",
          "size": 300486,
          "sha512": "156bed701b57b6bb875cf1ea62b41abd848a654b3f2e1c6aebd8d1a4ddfa001d2d74bed8a5dde8e4f31b2fec5e487a42c419d3c9865adb468c0aaddc74df62ec",
          "sha256": "1b3c9caaf1ce25a8dffcab5c5d9f4372b5c87562738507a60e776478a2454511",
          "sha1": "8d8a7bfc07b5019ea97ddd55fffbf7fc086ba5df",
          "md5": "06101425eb3ca59c0bdda0fceea0f3af"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-js-1.6.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-core-js-1.6.0-SNAPSHOT.klib",
          "size": 300486,
          "sha512": "156bed701b57b6bb875cf1ea62b41abd848a654b3f2e1c6aebd8d1a4ddfa001d2d74bed8a5dde8e4f31b2fec5e487a42c419d3c9865adb468c0aaddc74df62ec",
          "sha256": "1b3c9caaf1ce25a8dffcab5c5d9f4372b5c87562738507a60e776478a2454511",
          "sha1": "8d8a7bfc07b5019ea97ddd55fffbf7fc086ba5df",
          "md5": "06101425eb3ca59c0bdda0fceea0f3af"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-js-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-js-1.6.0-SNAPSHOT-sources.jar",
          "size": 98823,
          "sha512": "ee856863b9731b33442aff4e792634e4c82fc7573ad97fe77cde136f27039e6a8c5ad3e2129cc376e97818f50526aed3678661e9636e6c1a6c092c5107b81e80",
          "sha256": "ae496e1e0680d22b53aef5a2b93c380d7a49eb16d53b162e581f9eac6c96be0b",
          "sha1": "cc8bdb977e27c1a1a08b64f3c2d80cf4c8925d03",
          "md5": "5c2674182e001d77df2194ebb9923079"
        }
      ]
    }
  ]
}
