{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.6.0-SNAPSHOT/kotlinx-serialization-json-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-macosx64-1.6.0-SNAPSHOT.klib",
          "size": 247665,
          "sha512": "9f3fb332ec5791060f7cea10cf581424efc938128420416e5351e3f073ddd44b8a442011b1942500ece89fd31411d38d065788eb7985a0927769691e6a7057cc",
          "sha256": "6787782e304448d93e78783df0e608214412e20d9ee3dcd8f8226b8fa8dda1ba",
          "sha1": "85b1f4986dad3911a1479cb8b468f5948c095ecd",
          "md5": "860e41cf7ec9d988778b3a6247209156"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-macosx64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-macosx64-1.6.0-SNAPSHOT-sources.jar",
          "size": 73593,
          "sha512": "111f3c2443dbb3cb6537b5d9a92597b6c8b2bf9616833587dddfe2e80ccaf151d60b2201e7f535d22204a37cd56b0edde1a979eb6bd80b21f82bcfc03164f876",
          "sha256": "4b7dd8d46dd54a8f249db397553d290f77b5468477c849d25f8d6c4d52ca7e33",
          "sha1": "1d13131e61139f51287f933b0583331d3726e9e2",
          "md5": "bcc17f5e8e9f5b4f6e5d6dd5a816f90c"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-macosx64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-macosx64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ce76d42d0677bcd8cc662bb48b076c2c6dff304319458bec01d5e2519e19f1b090b77105295ed192c30d35c5d09901858fa6b7526502e7235af49ca6ad359cff",
          "sha256": "cc4aa7ae7b04d49a119a02c7a94d6ad1870a175d7f273424f3f479cc587f799c",
          "sha1": "d4e98ef0fe8b18b2ba02019bde6b8a2d97bc3fe9",
          "md5": "1a6db76e49923d721e8d6924036baf64"
        }
      ]
    }
  ]
}
