{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.7.2-SNAPSHOT/kotlinx-serialization-json-okio-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio.klib",
          "url": "kotlinx-serialization-json-okio-watchosarm64-1.7.2-SNAPSHOT.klib",
          "size": 15973,
          "sha512": "06602d4bcc3fabf9229262f46588274dccffc0e22ce9ed9d1b69c110a79afb686d075686a6a36fcf2d9f33edd3824b3390e5d8288ea373cf78499c2b403d69fe",
          "sha256": "fbe12b6c67dcf4882c466caf195dbf3d07bbee32fe75b25a186d777477400464",
          "sha1": "fc4b49796729d10ba056d60bcf4fb471fe3d1384",
          "md5": "afea70cf624fe0e20095f9df029b43b1"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-watchosarm64-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-okio-watchosarm64-1.7.2-SNAPSHOT-sources.jar",
          "size": 4356,
          "sha512": "55144ba96d1e9c232694de7d01f6acf19237125048cef3dd7fc474479a27ed8018a416990080a976f8dee57bb4a7bc4eb65b144f2428ee8f3863cecd52d3c669",
          "sha256": "7e663f91e65ee8fcc7445f525968dac33967ca0ab10d385971c69cad9230fb64",
          "sha1": "979622aac10b92f661a3a081ee3618ad989734f2",
          "md5": "95d88152c64308c2b2a586d3bbb181e3"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-watchosarm64-1.7.2-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-okio-watchosarm64-1.7.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "731dbb0857754930b99b53594709ba7860bc66a6c30d9746cff67d6e7dc516b5bf2364cc71850220633875e1e967392fd436c08ee59cc2788f02f4949fe208c0",
          "sha256": "997d492142fe2f0864c9ca49f53766f7a19bea2139b93eeba0faf810d2afc0af",
          "sha1": "f7a77910281164ae61728e25836c7a5101e3474c",
          "md5": "88e7d6ae2f6bf5fa1cb0313129a703e0"
        }
      ]
    }
  ]
}
