{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.6.0-SNAPSHOT/kotlinx-serialization-json-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-watchosarm32-1.6.0-SNAPSHOT.klib",
          "size": 247703,
          "sha512": "aa5064feca15d934fed6a28e3793e5c692ab463b6ef54c73c9bc8a4b49c17b3443b95c3972115fd3e69b3d958d059bf87fc0583cc2e9344a9ca3edbad1c20b7a",
          "sha256": "7c1d0bad774736a1e384d4334c5a263afc9cf163dc5c3f3941964cca5cb0500c",
          "sha1": "da12a920851ac216ebdcefe537558c91d1c4a8c1",
          "md5": "6e6623e829c9eee3d6410fd42dec6410"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-watchosarm32-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-watchosarm32-1.6.0-SNAPSHOT-sources.jar",
          "size": 73593,
          "sha512": "111f3c2443dbb3cb6537b5d9a92597b6c8b2bf9616833587dddfe2e80ccaf151d60b2201e7f535d22204a37cd56b0edde1a979eb6bd80b21f82bcfc03164f876",
          "sha256": "4b7dd8d46dd54a8f249db397553d290f77b5468477c849d25f8d6c4d52ca7e33",
          "sha1": "1d13131e61139f51287f933b0583331d3726e9e2",
          "md5": "bcc17f5e8e9f5b4f6e5d6dd5a816f90c"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-watchosarm32-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-watchosarm32-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ce76d42d0677bcd8cc662bb48b076c2c6dff304319458bec01d5e2519e19f1b090b77105295ed192c30d35c5d09901858fa6b7526502e7235af49ca6ad359cff",
          "sha256": "cc4aa7ae7b04d49a119a02c7a94d6ad1870a175d7f273424f3f479cc587f799c",
          "sha1": "d4e98ef0fe8b18b2ba02019bde6b8a2d97bc3fe9",
          "md5": "1a6db76e49923d721e8d6924036baf64"
        }
      ]
    }
  ]
}
