{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.7.2-SNAPSHOT/kotlinx-serialization-json-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-wasi",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-wasm-wasi-1.7.2-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-wasm-wasi-1.7.2-SNAPSHOT.klib",
          "size": 294997,
          "sha512": "6984131d6caedbec714ceb2d0c66998f3a919504ab74c3959a65117569d480af37215b779b357101a3d63bb9c2d3486382bda4fabaf72c1d669d5bc2c2c5adb9",
          "sha256": "caec46d07674f0e3c2652374daf787301f6fde56837653d68e2d4f785578f475",
          "sha1": "0bcd0719d945bbd7ad35d2ba0b8466bc17267770",
          "md5": "84694f423810b7286a3cb5f04832ad57"
        }
      ]
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-wasi",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-wasm-wasi-1.7.2-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-wasm-wasi-1.7.2-SNAPSHOT.klib",
          "size": 294997,
          "sha512": "6984131d6caedbec714ceb2d0c66998f3a919504ab74c3959a65117569d480af37215b779b357101a3d63bb9c2d3486382bda4fabaf72c1d669d5bc2c2c5adb9",
          "sha256": "caec46d07674f0e3c2652374daf787301f6fde56837653d68e2d4f785578f475",
          "sha1": "0bcd0719d945bbd7ad35d2ba0b8466bc17267770",
          "md5": "84694f423810b7286a3cb5f04832ad57"
        }
      ]
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-wasm-wasi-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-wasm-wasi-1.7.2-SNAPSHOT-sources.jar",
          "size": 80366,
          "sha512": "cf91dbff5b6a7b7c72d5b86a9912bf8055d7a25740aefe2a53d61d184dc7e9e07a92ada9b78abb3c00cc5a03ab8f7f7967fe2fac87958d2058e2135008a6d12b",
          "sha256": "2fe8da6a432f6477507cecc209c9006b935b1f6b5fd185b44355eaf882cc8d80",
          "sha1": "ddd44399aa9a3d9ba1725c5bc653c1319923c8fe",
          "md5": "508b9f56b66088c6ecfea80696d97211"
        }
      ]
    }
  ]
}
