{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.6.3-SNAPSHOT/kotlinx-serialization-json-okio-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio.klib",
          "url": "kotlinx-serialization-json-okio-mingwx64-1.6.3-SNAPSHOT.klib",
          "size": 18242,
          "sha512": "aec7a59f0b1ab91f02993a1094d2096d7fa002f8ea0d1e6024eb691b265ad397c414348db1340d6261135f0b61b9414f0e9117f122c0b1ca4ed1dbec4c014833",
          "sha256": "33ee112f5f67d610a1f052ad7e5cb29e51fc31e5174ef8a0e3ee5125329a0b73",
          "sha1": "53b8ddcd1924c1d7919fd5ad02a214a159883e0f",
          "md5": "ba1760f4726ddcb8e4378d77101317c2"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-mingwx64-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-okio-mingwx64-1.6.3-SNAPSHOT-sources.jar",
          "size": 4356,
          "sha512": "8a5eb4ef2bfba1b6b2b8bfa693f2d5060024ac3fddaa2cfc983642bb46a2e2bfaf060124fd36c8d78cb08b8d11ace39e4a044d0a82d952c051d7a66b3aaf16d1",
          "sha256": "f0593c18eb4f8ec337ce775fe7e2a0febbcee04f26afef935a69f3347d2c34a6",
          "sha1": "e6eb7473a38235959c4c5f2ab7921695b21f5c21",
          "md5": "1df8c3f6fa85629d9a5f920f46753a4d"
        }
      ]
    }
  ]
}
