{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.6.0-SNAPSHOT/kotlinx-serialization-cbor-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-linuxx64-1.6.0-SNAPSHOT.klib",
          "size": 86714,
          "sha512": "9d40a3fb2e69ab2da4449f075cf264dd98f41b9967cc3b585e07ed107a3b317ef03f91ce124ce35e5c0ed4e2d54bca9bfb8896b662501d81c773ae0d16abc681",
          "sha256": "ba19614ada690bd281e8a3411e83d77e46e80811c22132faf1a0c57f8e5cffc1",
          "sha1": "a745ed991e237d1243246dd266b9ef59ff24c5e8",
          "md5": "b7d1e839d04fef3b80d85e61ef7b1672"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-linuxx64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-linuxx64-1.6.0-SNAPSHOT-sources.jar",
          "size": 16435,
          "sha512": "826f0a085a07e9b8ae76dbb73b534140539ec5829964a46dad78baad71ed146d517b1a41e7c2221b66c79d41e75380236179f8050b9b611583bc52540200c3b5",
          "sha256": "bee65713d03f075601ee5ecc9b7605c684bc6c12cc77caaff28786a0724ece25",
          "sha1": "9238164915194e2d68f4fbc95967123362a232ac",
          "md5": "1914c2244541c5af3415b21d581ebc55"
        }
      ]
    }
  ]
}
