{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.6.0-SNAPSHOT/kotlinx-serialization-protobuf-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf.klib",
          "url": "kotlinx-serialization-protobuf-tvossimulatorarm64-1.6.0-SNAPSHOT.klib",
          "size": 120389,
          "sha512": "30054820073bd56db4905409aa2465e255ab55b48e02a7d002aa9101936719ed54dcce3dcd1ee64cf73f0e0bef9ad1be4897fa5644669cb2b5a19dd032cb69f5",
          "sha256": "367af71badab6b18bd3011f897ba9aeddca0890cfd4f39f747e30fc2ccdf5c0e",
          "sha1": "c155ce5713a84464423d2fa1a4c4de9236f637ef",
          "md5": "7ec743eae72acc29c1966900c1ca560d"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-tvossimulatorarm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-protobuf-tvossimulatorarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 28577,
          "sha512": "57f751425cedd7f474c3b7a7f9d0e57c449b7ace8b7cdad976e71480ac29bdd0708eed515511bb1ae44b634353d87c05166c410cfb86d121fb36331c599c421b",
          "sha256": "4b5c6ca97b4c62ee4e909132b80d1c9f487ec4ddd08b3a0014ac19e49cff28bd",
          "sha1": "096572e14d25cd2bca86b475346262d9be242407",
          "md5": "7cfed7b824307d147483c6794f150ea6"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-tvossimulatorarm64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-protobuf-tvossimulatorarm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b7a73b08b728a26e796129c1a6cb2de5c526406d8a56c5d955b71191db2218eaf695bd731a8a18857b7716af8137704a62dd5dc21d9700054a48299be658900a",
          "sha256": "75181d98138cedbed5b4a620e19a5ebc282316803afc12e5ac00b235cdf7ab15",
          "sha1": "c3a567eb5d3166ec132b1f05669641632f68ea0c",
          "md5": "4a625cf91fef6c3beb27701e4105b3bd"
        }
      ]
    }
  ]
}
