{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.6.3-SNAPSHOT/kotlinx-serialization-json-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-iossimulatorarm64-1.6.3-SNAPSHOT.klib",
          "size": 272704,
          "sha512": "218b72e6840d20fa069d4015beb4748b4a4f3007cdc64eedde5869cdb255b2b070121ca29405272d631db7d987497023cab5e7169b5afcd25b4a5af3a05c9c29",
          "sha256": "3eaa167a8633b6ce591784d35ca3918137af2f72b341b4db49d6f15770c65bec",
          "sha1": "98a5177490dcefb609fa01745e45521058091976",
          "md5": "b3c2ee5e9cc2417df5aeaf63676f26d8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-iossimulatorarm64-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-iossimulatorarm64-1.6.3-SNAPSHOT-sources.jar",
          "size": 75475,
          "sha512": "612d68f19e08ba97da2af29681762e44a75715696c2f7c701e5827e24ae79cfcff41806ae10c6495987ff18b3f858b7ac16fffe012e402d60161b7eac4537f77",
          "sha256": "1d6191146cc5fca60a4b4e7dffd6498fe06eada634f20649a58eb2539fc1133c",
          "sha1": "fafaa45e226942a5c14bb7a4ab117ee231fdd365",
          "md5": "918557f577b85f53cf8e9eaef52890c3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-iossimulatorarm64-1.6.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-iossimulatorarm64-1.6.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "c064f214d61df7f3c51d8ff793ba6a030f4a04bd9c6bd0b9bf5214b7ba3656048db6ee076060783aad62ae8cb94ce6b831dfabc7faaba87399ecfb10f63a2e28",
          "sha256": "284893a7a63363ee294431cd53145169f0d86f16074554b17026fce204714378",
          "sha1": "c51e9402cba5ec9effee3000c2e9b4d09f8b4fe4",
          "md5": "e688ae97761de3f140e437c09692256a"
        }
      ]
    }
  ]
}
