{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.0-SNAPSHOT/kotlinx-serialization-core-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-androidnativex64-1.6.0-SNAPSHOT.klib",
          "size": 282822,
          "sha512": "efb5aecb62c0758ea643c93f46226996fb8106c9ae8f481e81469b6fbb3f3fa9baacf207347cc2c8de8e9e06d793fdbb992f00575daec57d882b2481b5bef424",
          "sha256": "82db95f4824bb86235f61982ea19ddd8cc069a960fd28a35d8c38e1ec704c843",
          "sha1": "97360bf0a9ea9cdfe135c23a9ced29522cb1a294",
          "md5": "a25d61679482949f4b2b967af32c684a"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-androidnativex64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-androidnativex64-1.6.0-SNAPSHOT-sources.jar",
          "size": 98744,
          "sha512": "9b95c76e30bb8ecd501e72c05b4a7fecb351ed396654d6abc4944518c7a141faf89952cc3335e885c8eadb19a03e9e6abe5b7ee15d6c3be159307b42fc386cab",
          "sha256": "7b13559e42f741cfd0edfe3accc84610b2743d081de6ca2a68fdb65bd1cc4b95",
          "sha1": "4057cd6951920634815ee921e2ef63e2b9534fd1",
          "md5": "388393a5b3bfd3ade0a928af9435f9fa"
        }
      ]
    }
  ]
}
