{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.8.0-SNAPSHOT/kotlinx-serialization-json-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-macosarm64-1.8.0-SNAPSHOT.klib",
          "size": 305704,
          "sha512": "6c7bbded62089ccaebf10db2dbfb3f6265282842bd889e16cc189671c63633ceea0779ccfa74a5331da33cc4573b6913b3454fd35256e72866ffb0c01ea942d9",
          "sha256": "06d37022cfeffdff1bc1113589590b742721cdce57cca8bb497c1ecc1a57f565",
          "sha1": "b14f8e767850a2521e27bf9155aeb193c3409c94",
          "md5": "1f38d9b3e2761a8e3ea6fced32c2c126"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-macosarm64-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-macosarm64-1.8.0-SNAPSHOT-sources.jar",
          "size": 82263,
          "sha512": "fa81d51c2caaa083ee5ba1058cf49820317bcf3b431e43f78ea4b813552e59be410ca21b10c1bd8387203022db898bb1d105997b55ab9d0930e9ede837a6ae93",
          "sha256": "dea46f9bca65fffb9dafff1c8c13430dfc17ba7f333987936fb4767cfc721fb0",
          "sha1": "39f0c69b8a42b06bb48e11eef5a6c7f2ce9fe116",
          "md5": "fc7cbbf00dc2f97b3c2ae1a0ab090b8b"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-macosarm64-1.8.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-macosarm64-1.8.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e31b66b838993f40c701e164f0de7e2f0a4637d10acb029b63b2c9b2e843ac5c2fd3acb85277bf86b21468f0181ccb4ab1bbd58d62a4642c29a9d7401dd7efed",
          "sha256": "e496c2fc4c841593e911f146c08bf895d69577b6b25d68fe25ccc707bdfb215b",
          "sha1": "e38dd752cfd4df0d6bb3f4c23649f4c29ec7408e",
          "md5": "8ec0e6230b84fd7effd4754146ca7499"
        }
      ]
    }
  ]
}
