{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.7.2-SNAPSHOT/kotlinx-serialization-core-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-tvosx64-1.7.2-SNAPSHOT.klib",
          "size": 325605,
          "sha512": "2a72fcd36b57b570d54445e6d573b0884b2f8f4a7befe877df2a95ca4aa5c7bf4c3d745afca40f8f687424c05783f39a020da2a9ae553a9406a7d2c9d1a9f116",
          "sha256": "0277ad8c7a7c2bb083a15eaf9ab1eea856cfe6b8c0ee1913a3360ff214b63f72",
          "sha1": "33376810e1ec564d99f1ffbdcf5c22013b6d11c3",
          "md5": "56089aac9bd58b52f015d63252ee41c7"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-tvosx64-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-tvosx64-1.7.2-SNAPSHOT-sources.jar",
          "size": 100345,
          "sha512": "869512f66d16d8a09099e39b29da203802cf7d1779f3b8fbea2a6069da6e3bad475d4b60bfd5553c8e546cb97222ee78d97d92a4cd96ca1af1b362901e122346",
          "sha256": "ab430185de994e88bf871f962f877b3e030ec35137beef0c2973f6dc0e14b55f",
          "sha1": "171da31ef477424df6c88cc77940d3fa10617b32",
          "md5": "afe36c66a49b324e693db0b6fa8612f7"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-tvosx64-1.7.2-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-core-tvosx64-1.7.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ff69ac4747620132946bd698c74ca18230293932b125ff5dc38b3242714662f59cbfd19f99a1fe371f1e55a6f63372ff7842830507a14af78254619da28e05d2",
          "sha256": "97cd4cb084b062cb06206222a27e29bcd104258a9f9c3c897db5dfb126c8ded3",
          "sha1": "9870cd76532a27d90e759ce97bdc3800ac85f24a",
          "md5": "0d8247f38622dea4247aee5d420a43e0"
        }
      ]
    }
  ]
}
