{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.0-SNAPSHOT/kotlinx-serialization-core-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-macosx64-1.6.0-SNAPSHOT.klib",
          "size": 282805,
          "sha512": "29734810e2d39c174ba031e367101b6b9124fb59cd71f0dfa323b8d369f6096f57b22d7b983bd9fc470385eeb36261d18c301261b33c69e6c51824644c1b7ad7",
          "sha256": "dd5fcc744c4d394e48f3fb32e8dccbba01c2bfe5fa67c0c5868ea29a39c223ad",
          "sha1": "5909b02f8c87b8a68b0e633065c8280ec6e30be0",
          "md5": "1cf606365f53a01b2fa44292ca26080c"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-macosx64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-macosx64-1.6.0-SNAPSHOT-sources.jar",
          "size": 98744,
          "sha512": "9b95c76e30bb8ecd501e72c05b4a7fecb351ed396654d6abc4944518c7a141faf89952cc3335e885c8eadb19a03e9e6abe5b7ee15d6c3be159307b42fc386cab",
          "sha256": "7b13559e42f741cfd0edfe3accc84610b2743d081de6ca2a68fdb65bd1cc4b95",
          "sha1": "4057cd6951920634815ee921e2ef63e2b9534fd1",
          "md5": "388393a5b3bfd3ade0a928af9435f9fa"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-macosx64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-core-macosx64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cf9ef5990f3c3f04b3153e0acd09b83759984d76f73a67cc301eff5aad9b6ae9e8667e40bd4acb41f279483095ac1ae3209f66306f2cc13b2835a9bca2a3efa2",
          "sha256": "73b6af3b0597b4c22a340711c54cc3d7e06e1bb484e0e97e7977bc7574ed660b",
          "sha1": "8c314f28bf124e63e6d42c386ff476ed793b4238",
          "md5": "12f1e51ee2b405675d23997d16c614a1"
        }
      ]
    }
  ]
}
