{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.7.1-SNAPSHOT/kotlinx-serialization-cbor-1.7.1-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-watchosdevicearm64-1.7.1-SNAPSHOT.klib",
          "size": 94902,
          "sha512": "744b112513f55117a29f622ad9a40522bff34209856850a62e6d3321abcbeac37f64bc3f4440396584942bb0ea11ee56c5a8d0b236a2bf2b6f382effb0e098aa",
          "sha256": "2168482c79c3540f53d60ee4822cea4a4c131f9f051cb006f64514efcb56a202",
          "sha1": "a903ff038a0fe917f8985e67668e22afe33ddd15",
          "md5": "03ba0e356b12aa8132b97f6d4f3ced04"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-watchosdevicearm64-1.7.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-watchosdevicearm64-1.7.1-SNAPSHOT-sources.jar",
          "size": 18897,
          "sha512": "a63dc917312b163f69d490eda6a6ccc95d491217b78b5784ea16477a1c7e049075af99797b7b74d6a5b28ba6a33e8fa05fbe4519d0e2a80b545eb7b76b21db2d",
          "sha256": "75bfaa21ec985c5dafbd48e87d30552ff3bf8d013e8c032bbf05bc88494cc856",
          "sha1": "183f81c6706540efe678229def6e145c2e0e396c",
          "md5": "1783d809cb809120d7b368a73df60961"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-watchosdevicearm64-1.7.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-cbor-watchosdevicearm64-1.7.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e31051d030023321b153e15e987e58eaeb95de169f43af17ce3af2759dce3148c4033c7281fe54fd1460309124837b8e2d8de3b36e3c2a8c5014ebc9678b2db6",
          "sha256": "73ebcf853b85557461e8289fc9df6e8ee701823548596863cf9e0eab0d679331",
          "sha1": "23d2c609619e24bee217da8259011536eb048d5d",
          "md5": "84183f56e75f61fb016986236911db25"
        }
      ]
    }
  ]
}
