{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.6.0-SNAPSHOT/kotlinx-serialization-json-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-iosarm32-1.6.0-SNAPSHOT.klib",
          "size": 247664,
          "sha512": "70bb17384cc37a7ae3bda7780bad2d8496c7fa746cf97526247c9ccb6df01f85cda670535557b2cf4e0b8f3e75d1c4936f23221d09a1c63afaf2c024dcd7a19c",
          "sha256": "80c761e98229a942ec39d287772bc057b11ac9c40e5b6f625e253ba498f2fbb2",
          "sha1": "6db4f7798bc92c502f9cf6c91b2e23b6d6523cbe",
          "md5": "cd6f9cb22740efbc5ac9780f0c11ddbd"
        }
      ]
    },
    {
      "name": "iosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-iosarm32-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-iosarm32-1.6.0-SNAPSHOT-sources.jar",
          "size": 73593,
          "sha512": "111f3c2443dbb3cb6537b5d9a92597b6c8b2bf9616833587dddfe2e80ccaf151d60b2201e7f535d22204a37cd56b0edde1a979eb6bd80b21f82bcfc03164f876",
          "sha256": "4b7dd8d46dd54a8f249db397553d290f77b5468477c849d25f8d6c4d52ca7e33",
          "sha1": "1d13131e61139f51287f933b0583331d3726e9e2",
          "md5": "bcc17f5e8e9f5b4f6e5d6dd5a816f90c"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-iosarm32-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-iosarm32-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1cc77a0ea3a2011438ef4ab404d84b208a74bdf1c45cf5feefc10afa23d9b6a85ce214ecc3d77dd7005cea7e683a0feddd8b1cd12d333f7e68d5811360a5cd38",
          "sha256": "6209806c68d0ec377d79c4e7dd13d269d1de5f7be091d73794e727156760d8b6",
          "sha1": "de409a175b065941f66123a0e40d42d46da3216b",
          "md5": "1548ad577b1d9e5ca38f9b5f608cc2f9"
        }
      ]
    }
  ]
}
