{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.8.0-SNAPSHOT/kotlinx-serialization-properties-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-watchosx64-1.8.0-SNAPSHOT.klib",
          "size": 18780,
          "sha512": "a287e34d91a0c7323d6ba6b5c5372b6c441200bb0c31d5e589a00dbaf9492aed1b7835d13b51fa45f116bea4285e877d6be4082626470d00da5210d6325c9024",
          "sha256": "c3c6a47f5d858df7a6759c90ebd236b9b0ec9007fac92eaaebaffd3bf9a65908",
          "sha1": "4ed452bbf13ad8b6e304a14f72e2012ae88105b4",
          "md5": "6ae2de55dab65152efb6be67caddda9b"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-watchosx64-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-watchosx64-1.8.0-SNAPSHOT-sources.jar",
          "size": 3692,
          "sha512": "59ddd7439185a552035f7e09e3bad84e212673bb218ba42b003ad79be221ffa9a231f4738de5eeb9a7a9955fcb9869ddd72958896104f6c7654afda9dfa4eecd",
          "sha256": "f0edaa0a99e24d8a9953ea734b3eb78428ec949dd568e1eb7125e604e6714831",
          "sha1": "0f16141a0888abd29bba2d9cd82aa4230daa7275",
          "md5": "1f1a044c083221b07767f71927933221"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-watchosx64-1.8.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-watchosx64-1.8.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "8f21b40e942780eee0f165524f1029d76e76a472eb1c738486f0c5b5d4427777710364ed9b85f4386f7caf1d9e2eef1a6621c59e9ea6086ba468e127fd8cbfca",
          "sha256": "c457d79a0ead31f1b105df46530a72b18b4354eb88cfbcdb6ac98707489c46f9",
          "sha1": "2db5e6064b7af8437040b41046fcca8c3b4c5ac8",
          "md5": "679df103af98b1d0da4a32d000c50124"
        }
      ]
    }
  ]
}
