{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.8.0-SNAPSHOT/kotlinx-serialization-cbor-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-macosarm64-1.8.0-SNAPSHOT.klib",
          "size": 92984,
          "sha512": "ac52d6488ae599b034870549d5975bf83c009b5e8537edfd35d8eb46bd065de91a23d35badf2494264b936428779ef672b28ba280a7112dd9c0abebd04144512",
          "sha256": "cf0d59014c683771c7aec97d757a554652238455e21ab7f3203d4ee8c7f66fd2",
          "sha1": "a23ef60c8debc86a1bf07dea6a7a20c7902d5ed6",
          "md5": "99054fd99ee9d0d3b03085608bf46d47"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-macosarm64-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-macosarm64-1.8.0-SNAPSHOT-sources.jar",
          "size": 24207,
          "sha512": "a6886a8a2a294780b6a715f4c13d11d584f4ae35beb80ff81849498069ea80560cd9cd29f478a30059de5b0dea9402ee5251d762c11c55ad8970c6022debabaf",
          "sha256": "02e95064eaebe90e7057626da1e41c2e5c710a8a28330df95dadff40e935c7ae",
          "sha1": "0733d6423ca1ee3ee0d2dd7ce117432bba6491ed",
          "md5": "d4b346b1845b2275ad3b2d6245f7cc24"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-macosarm64-1.8.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-cbor-macosarm64-1.8.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "390548991440e371cc46754784a92b800d8692db74ad6d9b886db20cd2ec2291e17c935e54d9270dbf624cf25c9134e0250cb55294c2620ca50c6a8988c01d57",
          "sha256": "0ecb9d88b675721591b7a1257463a4863fd91aae34c3d3caec53819584ad61b0",
          "sha1": "175b59047c610424000838c8f11ffcde4386b5f2",
          "md5": "1f72e609c34f10068ed871143d810097"
        }
      ]
    }
  ]
}
