{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.0-SNAPSHOT/kotlinx-serialization-core-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.6.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-core-jvm-1.6.0-SNAPSHOT.jar",
          "size": 418007,
          "sha512": "f18db85955c4a0e3d7b779421e0d127736b3e72254f6382e9ea02fd801804acacfe7df6421dbc973abf69d306f967e1faecb0d66b23ddcbe11d62b5c2445f4bb",
          "sha256": "7860cf372a4642c604a17282b5891df92387ee43bc4c29452a38946d836a691b",
          "sha1": "54d586cf6d45a7d3738bcd9e45fb32013876ce96",
          "md5": "1b99d530559952a7ee59443f1200e122"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.6.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-core-jvm-1.6.0-SNAPSHOT.jar",
          "size": 418007,
          "sha512": "f18db85955c4a0e3d7b779421e0d127736b3e72254f6382e9ea02fd801804acacfe7df6421dbc973abf69d306f967e1faecb0d66b23ddcbe11d62b5c2445f4bb",
          "sha256": "7860cf372a4642c604a17282b5891df92387ee43bc4c29452a38946d836a691b",
          "sha1": "54d586cf6d45a7d3738bcd9e45fb32013876ce96",
          "md5": "1b99d530559952a7ee59443f1200e122"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-jvm-1.6.0-SNAPSHOT-sources.jar",
          "size": 104396,
          "sha512": "64d007ae3621703dc7ecdbb3acdec8354c16a91aa465d6f3aa5f0235283fff0ae5c0018f9cceb8785353ae28ac29890a132e962a36c1c80cf459d8ec9db1ed37",
          "sha256": "f63c88523c69fe7be7b89f4464b707719a7a4effff90b66e213dde1e1ffba502",
          "sha1": "ba0a13ea78e48b16aafd82157973da9472aff844",
          "md5": "5ddcffc4918a240e60ef79881ecc5ddb"
        }
      ]
    }
  ]
}
