{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.6.0-SNAPSHOT/kotlinx-serialization-properties-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-watchosx64-1.6.0-SNAPSHOT.klib",
          "size": 19623,
          "sha512": "2518f744a8e89bffad423cec2174a7ef2ef1a70291c0f24c79901e7a543593467e8129068b54dbb9a0c52e351abc9313f11224219056d8ea06c60393f110bdd5",
          "sha256": "304419f1645e1e1941b3996d8624b9c0993bfaa12d248b94ee398594a3208ec1",
          "sha1": "30faaa68112cb3c68f49be8ba3d99ce3224f8420",
          "md5": "c061cf95e5c3468e08c2764f4b052caf"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-watchosx64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-watchosx64-1.6.0-SNAPSHOT-sources.jar",
          "size": 3766,
          "sha512": "a5bd31251a9c5283b9ee19bfccdab80225e5a9308307d07b0ac81d9950c9c08123c2dab9a208588943b7e7b08c3c9214017a378bc7c89fc0806edba717461b90",
          "sha256": "6271ba0299d4710db9c9bb890166eb8011dfe605ac60bb35043106e60971e815",
          "sha1": "1453a245d2574f74898d4f20b6f97b889b303660",
          "md5": "632184f558a1323015aa2d74c57bc53e"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-watchosx64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-watchosx64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cbe87a29d77eeab7d8e1afe1a51c4ba0128c2ab5a10c249ba7294acc4374d062fc4d400449c28d97ddf596ab6b8cf7502f17b4be47aa08cfec10c51de21724d9",
          "sha256": "9c7bf826195ae8b8ab8703290b6e97d32f189cb06751b227ba30b979dc1c2f01",
          "sha1": "b6d7e2a29e72822848abdbf06c32974af113c6a5",
          "md5": "e65f41fa877c9a58797fe49acf95ac01"
        }
      ]
    }
  ]
}
