{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-hocon",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.6.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.6.0-SNAPSHOT.jar",
          "size": 63344,
          "sha512": "f46cdc7664a42fc85e5121c8395837741d8acbf3485a7d2950a1541d7c91532d8aef291d0db296e18cab2fcba8c137390ddedbec8197202f935b58d15e60cf8d",
          "sha256": "088e289670d7b07205e21780cd3c33ef740d2b26ea1d520be6b0d36b514ccbc5",
          "sha1": "c7ca3af2aad043c4899cc627423dc118d62310a3",
          "md5": "5698f466137d2bfff6d2e0c3109e88f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-hocon-1.6.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-hocon-1.6.0-SNAPSHOT.jar",
          "size": 63344,
          "sha512": "f46cdc7664a42fc85e5121c8395837741d8acbf3485a7d2950a1541d7c91532d8aef291d0db296e18cab2fcba8c137390ddedbec8197202f935b58d15e60cf8d",
          "sha256": "088e289670d7b07205e21780cd3c33ef740d2b26ea1d520be6b0d36b514ccbc5",
          "sha1": "c7ca3af2aad043c4899cc627423dc118d62310a3",
          "md5": "5698f466137d2bfff6d2e0c3109e88f6"
        }
      ]
    }
  ]
}
