{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.7.2-SNAPSHOT/kotlinx-serialization-properties-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-androidnativearm32-1.7.2-SNAPSHOT.klib",
          "size": 18795,
          "sha512": "a1fef6d786249ba770612f11883c9007d7957658c94186cd61c01ad2628ab52cf2e23c9fb0d3897c9fd258785a3cbf591a34563f49ddf63b33d78dc54e0ccd6d",
          "sha256": "0357cda754abfb1815d34fa0d57c08cfd1bb817e661cc264a5eb2d7a97d18d21",
          "sha1": "bcdc3eb54d698748796a926523729b2646e61e07",
          "md5": "5ecd152e8bf7aeaa283902272626f94b"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-androidnativearm32-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-androidnativearm32-1.7.2-SNAPSHOT-sources.jar",
          "size": 3692,
          "sha512": "59ddd7439185a552035f7e09e3bad84e212673bb218ba42b003ad79be221ffa9a231f4738de5eeb9a7a9955fcb9869ddd72958896104f6c7654afda9dfa4eecd",
          "sha256": "f0edaa0a99e24d8a9953ea734b3eb78428ec949dd568e1eb7125e604e6714831",
          "sha1": "0f16141a0888abd29bba2d9cd82aa4230daa7275",
          "md5": "1f1a044c083221b07767f71927933221"
        }
      ]
    }
  ]
}
