{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.8.0-SNAPSHOT/kotlinx-serialization-json-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-androidnativearm32-1.8.0-SNAPSHOT.klib",
          "size": 305721,
          "sha512": "6c4218883b80e1367f08920072f8363a01d7e9c88b1a3209961e6613a8e7ecc4fb74a468b166ae156186ced7b1798cf0bf876336e12d7ac5ced398b0ce7422ba",
          "sha256": "7ddae7c6dcb244fc15388072ef5dc9d518e44b2292fb610031231215186fe172",
          "sha1": "28702c2cfde19d9ad9fb4709341d43a5f0087548",
          "md5": "7befa02da28a4fe0974942ee7d76c1a4"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-androidnativearm32-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-androidnativearm32-1.8.0-SNAPSHOT-sources.jar",
          "size": 82263,
          "sha512": "fa81d51c2caaa083ee5ba1058cf49820317bcf3b431e43f78ea4b813552e59be410ca21b10c1bd8387203022db898bb1d105997b55ab9d0930e9ede837a6ae93",
          "sha256": "dea46f9bca65fffb9dafff1c8c13430dfc17ba7f333987936fb4767cfc721fb0",
          "sha1": "39f0c69b8a42b06bb48e11eef5a6c7f2ce9fe116",
          "md5": "fc7cbbf00dc2f97b3c2ae1a0ab090b8b"
        }
      ]
    }
  ]
}
