{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.7.2-SNAPSHOT/kotlinx-serialization-cbor-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-watchossimulatorarm64-1.7.2-SNAPSHOT.klib",
          "size": 93970,
          "sha512": "9a385854f614a716576bb6c65d5c68a3e60db6420dac1c33cd82a6820103de2032be483762f59fc5737a51c9ce6f1e4cb19df83cec5c63c2fbdbfe40545ff1b8",
          "sha256": "eeef8c791880f517be9670d01375c84f65b56bc92f86ba97e39e69e75824130e",
          "sha1": "6fad751094c664831f018c9c732334777437639e",
          "md5": "2f205d6eb678b70f54668f3c9ecb7e0e"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-watchossimulatorarm64-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-watchossimulatorarm64-1.7.2-SNAPSHOT-sources.jar",
          "size": 19425,
          "sha512": "ffb1f6d8a03d975913e47a3b3294ac160b40497e9dc09c1851d8153136829678891b8f25e853f026c5bba13bd1cf683d32bb856d2cb5cfcc910d9fa59fb59558",
          "sha256": "c137c04407f379f0a1bfc3b98b5a5aa8b7dfbce5017e369b6613340b58a49e50",
          "sha1": "c0245c967deffe9275fd9240d005f1788f7597d4",
          "md5": "d2ffde2434a3f49dbe0c66fcd21a4768"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-watchossimulatorarm64-1.7.2-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-cbor-watchossimulatorarm64-1.7.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "6fb1459656ffc8a449f6f936e35bcb3aa3132354fb0a5087ef9ddc765684af6ec039d43649a902adc30b1f9674b8a7cc252bf3990f4eb1dbbba18c4d1014c8ba",
          "sha256": "2f1b5bbb3db41bafd6db88ef922d31639eafd979f0dafa6375388a7a68336462",
          "sha1": "540cb1354ca005adba08160700e8ce59acb2af37",
          "md5": "8bb9b0ba4b23b93facafdbb0f0bb25ca"
        }
      ]
    }
  ]
}
