{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.8.0-SNAPSHOT/kotlinx-serialization-json-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-watchosx64-1.8.0-SNAPSHOT.klib",
          "size": 305704,
          "sha512": "3eca6b95eab25d398ad5248979c10ddb6f76fd5ec9419e21b9baf37ac91746b4aba6256aad7ecedd42125c7363e37030c503b0e31e8a73afca832812c5b1441f",
          "sha256": "872dd106c0d0a9fbf64d0d12c2a051f9c4be836d6905c28c699790e894552a39",
          "sha1": "d817084e15e92cca381028a76323d7fa5e6c88d6",
          "md5": "406d158dd6ee80beb393d49673b54e58"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-watchosx64-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-watchosx64-1.8.0-SNAPSHOT-sources.jar",
          "size": 82263,
          "sha512": "fa81d51c2caaa083ee5ba1058cf49820317bcf3b431e43f78ea4b813552e59be410ca21b10c1bd8387203022db898bb1d105997b55ab9d0930e9ede837a6ae93",
          "sha256": "dea46f9bca65fffb9dafff1c8c13430dfc17ba7f333987936fb4767cfc721fb0",
          "sha1": "39f0c69b8a42b06bb48e11eef5a6c7f2ce9fe116",
          "md5": "fc7cbbf00dc2f97b3c2ae1a0ab090b8b"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-watchosx64-1.8.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-watchosx64-1.8.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "9815a8e082e17b3aecdbc275154ddaf25223d68aad6c88434c9d883f385678199a3c2b8102fa8fafa26104f7e6cee4e076440d030abbd20fd12ae7c755c0c97c",
          "sha256": "cd7bf7b916737cfcc8b525d7827204dc8a688e1c9ea0b064386f7a7177459076",
          "sha1": "ff4d7bc843fe453da20ffa7b0cf1de4b730e3a54",
          "md5": "416d1a6e11ae7a6a0da137aae6b490ef"
        }
      ]
    }
  ]
}
