{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.6.3-SNAPSHOT/kotlinx-serialization-properties-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-js-1.6.3-SNAPSHOT.klib",
          "url": "kotlinx-serialization-properties-js-1.6.3-SNAPSHOT.klib",
          "size": 18363,
          "sha512": "b1578b8c83a5a34d60912ded742238d071ba23d81827b309c289c5818bfcb03972355ae33c53cee4f042a41bd65acfbccefb9df4d7e79618309c4a0967335a89",
          "sha256": "f1ac3d9f4a4e9af6122ce91c71a59b609fc063bb63e5da5dcfe74d2a6f7a4e15",
          "sha1": "a0913d5950ba6de29238c2c5f5721af99df425cf",
          "md5": "abb7f96dbeeb1aab786a2419e29aac32"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-js-1.6.3-SNAPSHOT.klib",
          "url": "kotlinx-serialization-properties-js-1.6.3-SNAPSHOT.klib",
          "size": 18363,
          "sha512": "b1578b8c83a5a34d60912ded742238d071ba23d81827b309c289c5818bfcb03972355ae33c53cee4f042a41bd65acfbccefb9df4d7e79618309c4a0967335a89",
          "sha256": "f1ac3d9f4a4e9af6122ce91c71a59b609fc063bb63e5da5dcfe74d2a6f7a4e15",
          "sha1": "a0913d5950ba6de29238c2c5f5721af99df425cf",
          "md5": "abb7f96dbeeb1aab786a2419e29aac32"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-js-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-js-1.6.3-SNAPSHOT-sources.jar",
          "size": 3766,
          "sha512": "a5bd31251a9c5283b9ee19bfccdab80225e5a9308307d07b0ac81d9950c9c08123c2dab9a208588943b7e7b08c3c9214017a378bc7c89fc0806edba717461b90",
          "sha256": "6271ba0299d4710db9c9bb890166eb8011dfe605ac60bb35043106e60971e815",
          "sha1": "1453a245d2574f74898d4f20b6f97b889b303660",
          "md5": "632184f558a1323015aa2d74c57bc53e"
        }
      ]
    }
  ]
}
