{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.7.1-SNAPSHOT/kotlinx-serialization-core-1.7.1-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-iosarm64-1.7.1-SNAPSHOT.klib",
          "size": 325617,
          "sha512": "10447fbc1e16e1422e8238b95d33a0106a3c1497e0817b3affd3721000f32725e8114b3562f1799224b60d6063fb24d11d7648c3eda072641501b98c57c24f0f",
          "sha256": "3ac8cec740885ca0289d4c91ec9f6eec6f718c14df8f00350551f6b5cdb9090d",
          "sha1": "591bf789a5c2d421d955f5436d9c153d44696e49",
          "md5": "9b1b148718a77acbf9117fbd11c9e5e6"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-iosarm64-1.7.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-iosarm64-1.7.1-SNAPSHOT-sources.jar",
          "size": 100345,
          "sha512": "869512f66d16d8a09099e39b29da203802cf7d1779f3b8fbea2a6069da6e3bad475d4b60bfd5553c8e546cb97222ee78d97d92a4cd96ca1af1b362901e122346",
          "sha256": "ab430185de994e88bf871f962f877b3e030ec35137beef0c2973f6dc0e14b55f",
          "sha1": "171da31ef477424df6c88cc77940d3fa10617b32",
          "md5": "afe36c66a49b324e693db0b6fa8612f7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-iosarm64-1.7.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-core-iosarm64-1.7.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "26339b2329fdbf0fef15640747d5e468215e76947c1a2d4bd78c1172f7dd8c9545c47420f733bf1313e712f5018f110e6b73683113d32090b36f32c2cab91c68",
          "sha256": "a6f00746d51b8d72872c0466a799700a69f3aefd085a2987ae3d71d61442910f",
          "sha1": "4eca843d5145f755008a38e9e47b71de9c6b1daa",
          "md5": "17b3ebdead243c3f5e473de7de998a23"
        }
      ]
    }
  ]
}
