{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.6.0-SNAPSHOT/kotlinx-serialization-properties-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-watchosdevicearm64-1.6.0-SNAPSHOT.klib",
          "size": 19704,
          "sha512": "b840c3597590d6f89855c3461fa532a3c4f6dd640a769cda5c9ea0b00a9521b7b59a7c25a9767b1bb39da2b1aecbaaa657dfae940d004a5825c7455d47e306e3",
          "sha256": "67d47694f032dd887c194404c9c2194b2e31e0166fd0e48d598c0840959d012d",
          "sha1": "67b0813dcdf538dbc74e4902cf0239c91c492d6b",
          "md5": "7725e5b1ee69b9622d21dde79a7f2981"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-watchosdevicearm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-watchosdevicearm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 3766,
          "sha512": "a5bd31251a9c5283b9ee19bfccdab80225e5a9308307d07b0ac81d9950c9c08123c2dab9a208588943b7e7b08c3c9214017a378bc7c89fc0806edba717461b90",
          "sha256": "6271ba0299d4710db9c9bb890166eb8011dfe605ac60bb35043106e60971e815",
          "sha1": "1453a245d2574f74898d4f20b6f97b889b303660",
          "md5": "632184f558a1323015aa2d74c57bc53e"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-watchosdevicearm64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-watchosdevicearm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cbe87a29d77eeab7d8e1afe1a51c4ba0128c2ab5a10c249ba7294acc4374d062fc4d400449c28d97ddf596ab6b8cf7502f17b4be47aa08cfec10c51de21724d9",
          "sha256": "9c7bf826195ae8b8ab8703290b6e97d32f189cb06751b227ba30b979dc1c2f01",
          "sha1": "b6d7e2a29e72822848abdbf06c32974af113c6a5",
          "md5": "e65f41fa877c9a58797fe49acf95ac01"
        }
      ]
    }
  ]
}
