{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.6.0-SNAPSHOT/kotlinx-serialization-json-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-linuxx64-1.6.0-SNAPSHOT.klib",
          "size": 247666,
          "sha512": "8f89e8d6cc1244df86bf54f8c5f78562f084a2e114a746a190173bea20363ee0b337d7fda5185dc65625b79cbc46ce75dbb477ef3b2b08c697b08c9b6ced1fcd",
          "sha256": "8e773b33304d20055b9e50c3d7f14a4309c1a95fb40e54917553ae316f5d0e8d",
          "sha1": "a22d7218f21aa6dc8ed5b6548ac53416605523ab",
          "md5": "0503657e1a5859783c213b286b6746c1"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-linuxx64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-linuxx64-1.6.0-SNAPSHOT-sources.jar",
          "size": 73593,
          "sha512": "111f3c2443dbb3cb6537b5d9a92597b6c8b2bf9616833587dddfe2e80ccaf151d60b2201e7f535d22204a37cd56b0edde1a979eb6bd80b21f82bcfc03164f876",
          "sha256": "4b7dd8d46dd54a8f249db397553d290f77b5468477c849d25f8d6c4d52ca7e33",
          "sha1": "1d13131e61139f51287f933b0583331d3726e9e2",
          "md5": "bcc17f5e8e9f5b4f6e5d6dd5a816f90c"
        }
      ]
    }
  ]
}
