{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.6.3-SNAPSHOT/kotlinx-serialization-protobuf-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf.klib",
          "url": "kotlinx-serialization-protobuf-linuxarm32hfp-1.6.3-SNAPSHOT.klib",
          "size": 129227,
          "sha512": "b35f606317c8345239cc8a7f6ecf60fb09b2779cb89a6ea30bf9f17b77a52b1bcfec80df5ecdc517308472c064c3f823ed23feca5f67d9a303e6fbef2af62752",
          "sha256": "62f6c9ae7d37011a68b0cb5449be5c3cdb5ae1ebedf91e20b5e3c0398936b5a7",
          "sha1": "bd3993d358663af7c91c550bbabe1ce39eeaf02f",
          "md5": "583f835a52ff143c76c46259af0e5562"
        }
      ]
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-linuxarm32hfp-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-protobuf-linuxarm32hfp-1.6.3-SNAPSHOT-sources.jar",
          "size": 28555,
          "sha512": "3db518a375af956f733beb93049e518d5a1079996d3d3fdca57c78d24c26330a22e2f3b788b5f49cd6cdef8a41c05535020ececade2136971a7775251e581e87",
          "sha256": "82ff723972fbd6c1471af7e7ed88fe6c229b6edb47d74e6497e8965a8947913a",
          "sha1": "4e2889aded9e05f64bca7b3ebf5e51916c93e936",
          "md5": "5af205429bd7696619b37c7e0c2cf97b"
        }
      ]
    }
  ]
}
