{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.0-SNAPSHOT/kotlinx-serialization-core-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core.klib",
          "url": "kotlinx-serialization-core-watchosdevicearm64-1.6.0-SNAPSHOT.klib",
          "size": 282900,
          "sha512": "4aec8d956efd31c541392314fce8b8805566be61247896626af56bdbdcfe7d8b4e1d02e198876044fb6a335383cb6cd37fe498d6a84ef7650c7831f0d67992a1",
          "sha256": "2aa233c534c809aee4b7f2cbfe94b5c583264bbd6768e3b657f7abdea85e4ea1",
          "sha1": "ca376b24836f50a4c6bba810e44e3b83f1e691b6",
          "md5": "8367195c697ec7942dca0b9fc77b0a84"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-watchosdevicearm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-watchosdevicearm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 98744,
          "sha512": "9b95c76e30bb8ecd501e72c05b4a7fecb351ed396654d6abc4944518c7a141faf89952cc3335e885c8eadb19a03e9e6abe5b7ee15d6c3be159307b42fc386cab",
          "sha256": "7b13559e42f741cfd0edfe3accc84610b2743d081de6ca2a68fdb65bd1cc4b95",
          "sha1": "4057cd6951920634815ee921e2ef63e2b9534fd1",
          "md5": "388393a5b3bfd3ade0a928af9435f9fa"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-watchosdevicearm64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-core-watchosdevicearm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0e3c8b295c52cfee216f47787a07961886e504206a35492befaa6dcbf6c251b89487ea85f01faffe1f602fa55856e17a7f3fb00e9530d2b98bdd7dc6be0d6df3",
          "sha256": "3bbbaf3758781c9862a5857e417c0b302f69475c4d52a479b8ddaece0456ebd8",
          "sha1": "b4442c782142c24883c07c38a2455346deaaf368",
          "md5": "20597a311497dec1cdab28fa8fc08f69"
        }
      ]
    }
  ]
}
