{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.8.0-SNAPSHOT/kotlinx-serialization-cbor-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-tvosarm64-1.8.0-SNAPSHOT.klib",
          "size": 92976,
          "sha512": "6af3a062bdd363b078df7e55df9c6fd901f6aa7f231a7b5997ebef24332630e7659fe3c271bf7ec11e08cbc05bf23618fd7b91c2863a5954358dd37d06ab9ea6",
          "sha256": "d7770111e974cd1b04d6f3b6bb72ef23457c1f13588559138d785ecbadcf0bab",
          "sha1": "a311cf69adba5e090840a2f7d5e855e449d56d7f",
          "md5": "c508d8ca93bc18d25fe178ffd40388bb"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-tvosarm64-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-tvosarm64-1.8.0-SNAPSHOT-sources.jar",
          "size": 24207,
          "sha512": "a6886a8a2a294780b6a715f4c13d11d584f4ae35beb80ff81849498069ea80560cd9cd29f478a30059de5b0dea9402ee5251d762c11c55ad8970c6022debabaf",
          "sha256": "02e95064eaebe90e7057626da1e41c2e5c710a8a28330df95dadff40e935c7ae",
          "sha1": "0733d6423ca1ee3ee0d2dd7ce117432bba6491ed",
          "md5": "d4b346b1845b2275ad3b2d6245f7cc24"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-tvosarm64-1.8.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-cbor-tvosarm64-1.8.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "ce8c7bb29edca6398a4de17541b8a9b70c01e2472fdcaf746783ef01ce3db79154c167003390300fc25498d5156a78aa076c3d8cd053c1eb687b1b935dbed24c",
          "sha256": "98bbdc23dbd682adb2214c662957490aee9723e5dd958957815a973db1d6d7d0",
          "sha1": "bb63720a069b976e92ed1073d02e0301f8f626b9",
          "md5": "fa41ab78da809ec0118d48627c1e7efb"
        }
      ]
    }
  ]
}
