{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.6.0-SNAPSHOT/kotlinx-serialization-protobuf-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf.klib",
          "url": "kotlinx-serialization-protobuf-androidnativex86-1.6.0-SNAPSHOT.klib",
          "size": 120309,
          "sha512": "10bdc602c2e4bb76cffa17ac1c8df99f19b0db495e8a390f41ab9d487902580f930813f0ddc4808efe2e375e2e7e44ce3d3e1cc4553bc19357f4b2c463be6e65",
          "sha256": "8e31d2dad36c38bb481fc9858a8dc162415c1f681baf03fe6b881de4aff37cd0",
          "sha1": "14f06679abb30791b3c5d02360b0975b2f4394f6",
          "md5": "1ea77c1254e67642e53abb01cd9d45d9"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-androidnativex86-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-protobuf-androidnativex86-1.6.0-SNAPSHOT-sources.jar",
          "size": 28577,
          "sha512": "57f751425cedd7f474c3b7a7f9d0e57c449b7ace8b7cdad976e71480ac29bdd0708eed515511bb1ae44b634353d87c05166c410cfb86d121fb36331c599c421b",
          "sha256": "4b5c6ca97b4c62ee4e909132b80d1c9f487ec4ddd08b3a0014ac19e49cff28bd",
          "sha1": "096572e14d25cd2bca86b475346262d9be242407",
          "md5": "7cfed7b824307d147483c6794f150ea6"
        }
      ]
    }
  ]
}
