{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.8.0-SNAPSHOT/kotlinx-serialization-core-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.8.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-core-jvm-1.8.0-SNAPSHOT.jar",
          "size": 388661,
          "sha512": "2020f681f6009216218562cc2c56dc6d7a4b401edfac52b46db180ded80d88ba91cbd32baabcdef30a7543657b2ac92aace0f3c2d3ca69918e52aaaf4480d0c4",
          "sha256": "a37f00833f90d433bef2016915f13a6d83251a17177b3596c990d709e137f7f7",
          "sha1": "00381442729fb30deb7c0c91a9d9ca83ce536ca5",
          "md5": "e7b7283b5e38f97e79e8485fe273a404"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.8.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-core-jvm-1.8.0-SNAPSHOT.jar",
          "size": 388661,
          "sha512": "2020f681f6009216218562cc2c56dc6d7a4b401edfac52b46db180ded80d88ba91cbd32baabcdef30a7543657b2ac92aace0f3c2d3ca69918e52aaaf4480d0c4",
          "sha256": "a37f00833f90d433bef2016915f13a6d83251a17177b3596c990d709e137f7f7",
          "sha1": "00381442729fb30deb7c0c91a9d9ca83ce536ca5",
          "md5": "e7b7283b5e38f97e79e8485fe273a404"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-core-jvm-1.8.0-SNAPSHOT-sources.jar",
          "size": 105989,
          "sha512": "60539211a58c2d2a81faf7d042b2123eca2ecde493dead319e928481d2fbe90b55977480b1f2d67f90944513b8a0cf1977f45ae820ba2ae2e212b81005e13256",
          "sha256": "6707b350a9c9f875c0a00fee2cbe915e1a6371b0064265a7f5d2ec5fe89134d5",
          "sha1": "bfb5874824e00b6391489a26c83ff48a6f129b97",
          "md5": "0eebc7bde5469ad7487acf3909b8d874"
        }
      ]
    }
  ]
}
