{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.7.2-SNAPSHOT/kotlinx-serialization-json-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-watchosarm64-1.7.2-SNAPSHOT.klib",
          "size": 300060,
          "sha512": "217872e3e50a38f49985af20839877d12f4834702906393e7d64bbd19f3f997f2e5b471d7fb0d0addffe915d39ecc581edb27ac3a5ae9fb567d04b55688fcf3e",
          "sha256": "04ca8567cb460d5f3fe3a7f54e3b5bd0327e0afb5e0dadd8c6d9cedc3842c0a1",
          "sha1": "3ede20e47a2321fab80cc5261d7cf08b0144a6ef",
          "md5": "afdc89e2c712ed7fe0a736520235a673"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-watchosarm64-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-watchosarm64-1.7.2-SNAPSHOT-sources.jar",
          "size": 81199,
          "sha512": "905f6eeee1f702a18d953b628d95f4c8a3004cfc4208e9d17bb5ed4019b9317c685bd28c30818c47bd7015ab60527eaa12a3053eadd0ea464df3f23e984bab58",
          "sha256": "c38901a62bed97faea04105a47cc01a679de17c18d76d34a899a959a689f1030",
          "sha1": "da227f844c06ddba53c4e4b969beb3272d4977fb",
          "md5": "bea0bff577edd697079dd925410d272f"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-watchosarm64-1.7.2-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-watchosarm64-1.7.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "fb1a5f59ae11fd6a9c3cfd042d14fa3c8f00c436103067418115210bb052a0154c8d49c63c938bb993d29e8de2d21734737e256bc670e08a8ccbb21e57b0a621",
          "sha256": "b231b19a106dd3902d10107856232cf953732bcc315977c6f0f5e3eb67b2fef1",
          "sha1": "465876270d5865f834d3170f9667b95528ffa79f",
          "md5": "15dde9f6736a6051b4cddf269f6e6979"
        }
      ]
    }
  ]
}
