{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.6.3-SNAPSHOT/kotlinx-serialization-cbor-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-tvosx64-1.6.3-SNAPSHOT.klib",
          "size": 94368,
          "sha512": "75c23551285f3fae73d06e200c969b28ed6b210b8d4b72a81917a80599e6b99c8b012c9f172cb2e7e7b95ecde1e2f7417905d5ed1b9cbb9556048883502f6ca2",
          "sha256": "4de567da184dba6b0351efb9e6122c9957f930c1baeffd9733d3aefcff4dc6d0",
          "sha1": "9f132eadfc4ca782bac1a3794aa409467f4d75e0",
          "md5": "4ed35a01cba04fea1a464dd54cc0d396"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-tvosx64-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-tvosx64-1.6.3-SNAPSHOT-sources.jar",
          "size": 18803,
          "sha512": "b65500aabedc36290e381486cf16578212f19590a8dc6d904016561ce38c33a60d5ca4b6de0967aeab7ff453641e918433e8e378ce1cca381140b54cad2f218a",
          "sha256": "2690bfe0edf3cd4248a5f83b33da243aa1c48059e343af827fad7015b5c7546b",
          "sha1": "d3a66e03399f1509de27d127795c434227b6e86f",
          "md5": "d88d9a67fa0303780d9f120eb7cf078c"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-tvosx64-1.6.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-cbor-tvosx64-1.6.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "541ab835ab58bcb76aeeeff3e57d63c14d0c97c4f083761348f582efd70d91c9d353dc7aa488ee9834290aaf12ef0cf6f403ebc7e3583025b60b041226ede06b",
          "sha256": "15502399c7951eda02fe0eaad4dd0fcbb14ee0bb5d34322c1e9a237d2cce58f8",
          "sha1": "49431480fb233c5217584aa09c2df5f3b6c1b315",
          "md5": "5e6be3adf14ef563e942a28775061a94"
        }
      ]
    }
  ]
}
