{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json-okio/1.6.3-SNAPSHOT/kotlinx-serialization-json-okio-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json-okio",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio.klib",
          "url": "kotlinx-serialization-json-okio-macosx64-1.6.3-SNAPSHOT.klib",
          "size": 18358,
          "sha512": "11ca920a34b771b381aff24d40f268fbc8b53bb3a6ab3e2d8fe40f855ffd9a2b5a77496e299837660455e0eb1a88d98b8e72cc417a7b137d61d39c2af4283313",
          "sha256": "74c5fb9275a1882fffe0ee2c97e970a6aa46230d0187d8f70896cd48575260d7",
          "sha1": "df06282ae87c6f97a789db4a99ae659e9451a78e",
          "md5": "202fafd09e67ac506638421153232a89"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-macosx64-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-okio-macosx64-1.6.3-SNAPSHOT-sources.jar",
          "size": 4356,
          "sha512": "8a5eb4ef2bfba1b6b2b8bfa693f2d5060024ac3fddaa2cfc983642bb46a2e2bfaf060124fd36c8d78cb08b8d11ace39e4a044d0a82d952c051d7a66b3aaf16d1",
          "sha256": "f0593c18eb4f8ec337ce775fe7e2a0febbcee04f26afef935a69f3347d2c34a6",
          "sha1": "e6eb7473a38235959c4c5f2ab7921695b21f5c21",
          "md5": "1df8c3f6fa85629d9a5f920f46753a4d"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-okio-macosx64-1.6.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-okio-macosx64-1.6.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "0dff0bac8eed23e8564cc268576459ad66f38b7779d1897d78f3ae375040c947c8a1390f2fd83a2755db280afae4fd98e0ebf63f47ce1830f4881426e0e79088",
          "sha256": "47711748ff09e06bb52bb0bc7777d67bbe28c6d97ff511f433bb8e0fa9afea9a",
          "sha1": "f6dc0083960903eb6158a9706bb908157153f5a4",
          "md5": "248ec8138229d9273a26279e4b4cf18d"
        }
      ]
    }
  ]
}
