{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.6.3-SNAPSHOT/kotlinx-serialization-properties-1.6.3-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.6.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-iosx64-1.6.3-SNAPSHOT.klib",
          "size": 21190,
          "sha512": "50a65fe7fa02f813121af3a0419e1ab7d5f3abde816728436a16945ede4354d61428cdee4d1dcedb9fa954d7461ac9c4f11a9ffc694417a33827e19f116e4880",
          "sha256": "8a4a42ff6cdaa631356ab7319838b7743382546a84b5ad43d2fbab49a41b4aa6",
          "sha1": "ac676e1e49d945f45c2a7ed875ce64a6ed080cf1",
          "md5": "eb27150d969f2e9c5a71ab4b38851623"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-iosx64-1.6.3-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-iosx64-1.6.3-SNAPSHOT-sources.jar",
          "size": 3766,
          "sha512": "a5bd31251a9c5283b9ee19bfccdab80225e5a9308307d07b0ac81d9950c9c08123c2dab9a208588943b7e7b08c3c9214017a378bc7c89fc0806edba717461b90",
          "sha256": "6271ba0299d4710db9c9bb890166eb8011dfe605ac60bb35043106e60971e815",
          "sha1": "1453a245d2574f74898d4f20b6f97b889b303660",
          "md5": "632184f558a1323015aa2d74c57bc53e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-iosx64-1.6.3-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-iosx64-1.6.3-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b65cabe3de5fcceacb40f366208db4aac970e712e09f3608ed8380e6993cc33679aec4e3d8054b1c3f9a6cfc93557d84931d1d2577e4e273dc5ae7965bca1529",
          "sha256": "b340ce587155c1d19a667571c077390fa6e5f89020363dd0af9a84ad62ad6790",
          "sha1": "1c6525eead11cb21f4eefb1e83c7bf54fb080732",
          "md5": "d578cb1545314ec52600142afebfff90"
        }
      ]
    }
  ]
}
