{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.6.0-SNAPSHOT/kotlinx-serialization-json-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-js-1.6.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-js-1.6.0-SNAPSHOT.klib",
          "size": 295789,
          "sha512": "da928993c69f4d2264ff62e164ac8394a330202b7ba8b8dfc4b42a527eeacc939ddb57810adea7d35c70d2376d5292142aa0162ee4d99eb66a437bfb69564b82",
          "sha256": "1c72cd57af5ae2b0eead485bdbbe3be137c31d433c2c39b4cbaf2aa71bfad4e6",
          "sha1": "da457f9436cd3218e63daf304064ca9f8f3311ba",
          "md5": "f4a1cd48a4003d2c94d841b719612a40"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-js-1.6.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-json-js-1.6.0-SNAPSHOT.klib",
          "size": 295789,
          "sha512": "da928993c69f4d2264ff62e164ac8394a330202b7ba8b8dfc4b42a527eeacc939ddb57810adea7d35c70d2376d5292142aa0162ee4d99eb66a437bfb69564b82",
          "sha256": "1c72cd57af5ae2b0eead485bdbbe3be137c31d433c2c39b4cbaf2aa71bfad4e6",
          "sha1": "da457f9436cd3218e63daf304064ca9f8f3311ba",
          "md5": "f4a1cd48a4003d2c94d841b719612a40"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-js-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-js-1.6.0-SNAPSHOT-sources.jar",
          "size": 80049,
          "sha512": "d271bcca1787d105a1a6a38c52294cb7cba307441f4b71ef30b8ee78b6fc14a2bede89c0cdca28f3e3f33e612fc4c685cdb3e7316067b09f34ce7ebac2e00036",
          "sha256": "5d7f3aa677a5a7e35d86d1b9f94821ed6b8540bdbf0ca73e17f4a19f5a4c1ab3",
          "sha1": "a820681300421a8cc384a6d19b5f3c427c6b733b",
          "md5": "e3de2bcc64e6f3a380d3b8818345ffbf"
        }
      ]
    }
  ]
}
