{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.7.1-SNAPSHOT/kotlinx-serialization-json-1.7.1-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json.klib",
          "url": "kotlinx-serialization-json-iosarm64-1.7.1-SNAPSHOT.klib",
          "size": 300024,
          "sha512": "62435aba388fa780b560d32cc484643cf5a44434971a5b1b6dce5956a6f8a57a21c9411d59cf77641f0c55c5d2277afde34080eee9e5d280a899680e5d6dbcb6",
          "sha256": "af154badb8b4a06422bb375a3b8e3f9949b3bfc23517d918dff80cc2aee1a81c",
          "sha1": "f847eb651859de55203a6776b908ec3c0c313c3a",
          "md5": "b8689055000f999f966ef6ec7bff3bce"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-iosarm64-1.7.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-iosarm64-1.7.1-SNAPSHOT-sources.jar",
          "size": 81199,
          "sha512": "905f6eeee1f702a18d953b628d95f4c8a3004cfc4208e9d17bb5ed4019b9317c685bd28c30818c47bd7015ab60527eaa12a3053eadd0ea464df3f23e984bab58",
          "sha256": "c38901a62bed97faea04105a47cc01a679de17c18d76d34a899a959a689f1030",
          "sha1": "da227f844c06ddba53c4e4b969beb3272d4977fb",
          "md5": "bea0bff577edd697079dd925410d272f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-iosarm64-1.7.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-json-iosarm64-1.7.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "7515f0d7915c8969eefa3cddfc823fb1a57818829e264570d5ee43eecd1b9ae2b3e63b6c2297fdc4ecf5743f8f1a68b19dba2ab5248a6ea02e104aa9c7d4892f",
          "sha256": "8fcbacfac2a1fe4913641bb704acd2f711956dfad74d6b42b93d659e8f2967eb",
          "sha1": "0218aa3afd6d67482fad3d6accf2af7ed388472f",
          "md5": "97bd0d92b62fdb7fc9fdd40fd5f28a4c"
        }
      ]
    }
  ]
}
