{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.6.0-SNAPSHOT/kotlinx-serialization-properties-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-tvosx64-1.6.0-SNAPSHOT.klib",
          "size": 19596,
          "sha512": "8f87452b1d7483843572282776697e268c730d775bf801ec2d6971a1117308980eec3957e49443467b0663e63a5cdd38881d5d62e3d809e2dc4bbfa307f5685c",
          "sha256": "30423fe0919e724b4237ffd0c30fc1175115bf4136f2fa13b37a53fd794248db",
          "sha1": "807ea6a05ffd57539eb4fa36947359bfb1c5dec6",
          "md5": "3bf1473baefb9269b2b82d8df505cb62"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-tvosx64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-tvosx64-1.6.0-SNAPSHOT-sources.jar",
          "size": 3766,
          "sha512": "a5bd31251a9c5283b9ee19bfccdab80225e5a9308307d07b0ac81d9950c9c08123c2dab9a208588943b7e7b08c3c9214017a378bc7c89fc0806edba717461b90",
          "sha256": "6271ba0299d4710db9c9bb890166eb8011dfe605ac60bb35043106e60971e815",
          "sha1": "1453a245d2574f74898d4f20b6f97b889b303660",
          "md5": "632184f558a1323015aa2d74c57bc53e"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-tvosx64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-tvosx64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "cbe87a29d77eeab7d8e1afe1a51c4ba0128c2ab5a10c249ba7294acc4374d062fc4d400449c28d97ddf596ab6b8cf7502f17b4be47aa08cfec10c51de21724d9",
          "sha256": "9c7bf826195ae8b8ab8703290b6e97d32f189cb06751b227ba30b979dc1c2f01",
          "sha1": "b6d7e2a29e72822848abdbf06c32974af113c6a5",
          "md5": "e65f41fa877c9a58797fe49acf95ac01"
        }
      ]
    }
  ]
}
