{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.6.0-SNAPSHOT/kotlinx-serialization-properties-1.6.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.6.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-macosarm64-1.6.0-SNAPSHOT.klib",
          "size": 19624,
          "sha512": "80a5a4b598f48f1cec10b255a5c56c42de43d0ae78262b84ce7563dc1ca3ea9a89057b14acb6a5e55a86092bdef60c04cc5301a4bfd79f1f6a9b0deb87e9936b",
          "sha256": "a8c78b187e480415a7fc21162ed71d4eb3c3b888e44cd773fadabb8d2ca6e1cd",
          "sha1": "aa4535ee9adb8f09d276f57b864b5f8934975ad2",
          "md5": "fd89708b5c91614b702d69cddb365de1"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-macosarm64-1.6.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-macosarm64-1.6.0-SNAPSHOT-sources.jar",
          "size": 3766,
          "sha512": "a5bd31251a9c5283b9ee19bfccdab80225e5a9308307d07b0ac81d9950c9c08123c2dab9a208588943b7e7b08c3c9214017a378bc7c89fc0806edba717461b90",
          "sha256": "6271ba0299d4710db9c9bb890166eb8011dfe605ac60bb35043106e60971e815",
          "sha1": "1453a245d2574f74898d4f20b6f97b889b303660",
          "md5": "632184f558a1323015aa2d74c57bc53e"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-macosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-macosarm64-1.6.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "80545b0792a4d401b4d9d3fa777f5aaaf2a5cdc82b6226862e3e002bfb0e43bf78b64ea85d9bbdd09e57318c8fb291c9dcf84417d639f99d761c7606859b0134",
          "sha256": "c5f2b51b6fee3ae708110ae52d67aac99283e9afd866af2b12c9d2cb1f969263",
          "sha1": "2cb5477ebf290137c7c96095e4043953210a21c4",
          "md5": "17e8a6108ae9dc18ae4de61964928261"
        }
      ]
    }
  ]
}
