{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-cbor/1.7.2-SNAPSHOT/kotlinx-serialization-cbor-1.7.2-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-cbor",
    "version": "1.7.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor.klib",
          "url": "kotlinx-serialization-cbor-watchosarm32-1.7.2-SNAPSHOT.klib",
          "size": 93885,
          "sha512": "4de3430f7fd88520944c550bec18d0905a8798f569feddbedbcac95d7103472adce3dbd90d961c2adb3752ce8ff5eef6a7dbbf4b89d7c1e26fbac5d1f5404cf9",
          "sha256": "d64ee6b61b481ae145f72d7233869da0b09eb049deb0cf7683bf67321c3a8221",
          "sha1": "59ab7cc56713383f56e6b3918d8c91f2b282bfd1",
          "md5": "c0d1ef281d625756fdfe7b1629c4e92b"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-cbor-watchosarm32-1.7.2-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-cbor-watchosarm32-1.7.2-SNAPSHOT-sources.jar",
          "size": 19425,
          "sha512": "ffb1f6d8a03d975913e47a3b3294ac160b40497e9dc09c1851d8153136829678891b8f25e853f026c5bba13bd1cf683d32bb856d2cb5cfcc910d9fa59fb59558",
          "sha256": "c137c04407f379f0a1bfc3b98b5a5aa8b7dfbce5017e369b6613340b58a49e50",
          "sha1": "c0245c967deffe9275fd9240d005f1788f7597d4",
          "md5": "d2ffde2434a3f49dbe0c66fcd21a4768"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.2-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-cbor-watchosarm32-1.7.2-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-cbor-watchosarm32-1.7.2-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "114f39ed55a946346090afa0b3326e8d37984d147d3d6c0408ae9c663f9470073216fcdf75810e2936bb1a50e0c8536c7a2a0ad7a3902e6d99d35f5dac2f8ab9",
          "sha256": "852870f77e512b3e42549301a50970853e16fc56b5ad89a79c8f72f222d8849d",
          "sha1": "54036aed6dc53eace99768ce92f6da1c6e865f55",
          "md5": "23109167de7db19748877b9d45990469"
        }
      ]
    }
  ]
}
