{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.8.0-SNAPSHOT/kotlinx-serialization-json-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.8.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-jvm-1.8.0-SNAPSHOT.jar",
          "size": 270653,
          "sha512": "465b9c05248e9ad359fde9601b992461b8a88a731cdedae54caf0983eb5a2bdf6864c509cddd096505e8192c6a73c40c8e6e54c13445ec68c16276e339424085",
          "sha256": "ab6f1b6e8c70899d8c41f2be5c391d357840f1429b151f4dfb07271029083316",
          "sha1": "c2a4c17f9246285d862cbe1f03d6f8e0848d1958",
          "md5": "3f1263bddd1af097590e36c33a897850"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.8.0-SNAPSHOT.jar",
          "url": "kotlinx-serialization-json-jvm-1.8.0-SNAPSHOT.jar",
          "size": 270653,
          "sha512": "465b9c05248e9ad359fde9601b992461b8a88a731cdedae54caf0983eb5a2bdf6864c509cddd096505e8192c6a73c40c8e6e54c13445ec68c16276e339424085",
          "sha256": "ab6f1b6e8c70899d8c41f2be5c391d357840f1429b151f4dfb07271029083316",
          "sha1": "c2a4c17f9246285d862cbe1f03d6f8e0848d1958",
          "md5": "3f1263bddd1af097590e36c33a897850"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-json-jvm-1.8.0-SNAPSHOT-sources.jar",
          "size": 89071,
          "sha512": "018ebbb9b2914079803f4fb559bfdf36b2ed3a0df96e6238961a1400421fa262452b5d86f222cdf660a8316986c5e0c5a5d0e4a324837e0d2b0c3cd333cb0e42",
          "sha256": "7ebec244b7ea952d7fa4e092c969839134e4432261eb08c014643a91dd3781be",
          "sha1": "9e32a97a7f1395df46951ce5cc9d22efac7959fa",
          "md5": "3d4a69e43606d70356cec17e015bd161"
        }
      ]
    }
  ]
}
