{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-properties/1.7.1-SNAPSHOT/kotlinx-serialization-properties-1.7.1-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-properties",
    "version": "1.7.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties.klib",
          "url": "kotlinx-serialization-properties-iosarm64-1.7.1-SNAPSHOT.klib",
          "size": 18762,
          "sha512": "1b87e206d46dd0cfc1668bfa9c24dc3c5b785048b8cd32ea63c6502c81bf70d2bc7cf464a9aa4938d39b4a6dbbfeea26c3b0477da5a9f1b2ddd255a9ef1b7c50",
          "sha256": "6cdfcb7fabcf048229fc391c304030c9fa646ebbaf80569fd9c3d420eabe6f59",
          "sha1": "e7c1d2c90e899f34cb1d2cc8c2f290f5de04dfc3",
          "md5": "7b29cc9541e19c6f55868c0f7ede52c7"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlinx-serialization-properties-iosarm64-1.7.1-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-properties-iosarm64-1.7.1-SNAPSHOT-sources.jar",
          "size": 3692,
          "sha512": "59ddd7439185a552035f7e09e3bad84e212673bb218ba42b003ad79be221ffa9a231f4738de5eeb9a7a9955fcb9869ddd72958896104f6c7654afda9dfa4eecd",
          "sha256": "f0edaa0a99e24d8a9953ea734b3eb78428ec949dd568e1eb7125e604e6714831",
          "sha1": "0f16141a0888abd29bba2d9cd82aa4230daa7275",
          "md5": "1f1a044c083221b07767f71927933221"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-properties-iosarm64-1.7.1-SNAPSHOT-metadata.jar",
          "url": "kotlinx-serialization-properties-iosarm64-1.7.1-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "65a0d6277841ab2cb5fc29a83eb645d3ae510eee2c0790b992021de97c799f183bf9fe455b77fd70e96a31045a9d4d9acdd08a48a282f1436fd4213f3b9f2720",
          "sha256": "2452e2e81a88e638cd7ece2aa51d7bc3712a9eec023ccae484f7ed6744649bbc",
          "sha1": "4f391a5d57efb1b2efde5a7c1476e2fb12415328",
          "md5": "f4d295062e33c0ce9c01695960004499"
        }
      ]
    }
  ]
}
