{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-protobuf/1.8.0-SNAPSHOT/kotlinx-serialization-protobuf-1.8.0-SNAPSHOT.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-protobuf",
    "version": "1.8.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-wasm-js-1.8.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-protobuf-wasm-js-1.8.0-SNAPSHOT.klib",
          "size": 147911,
          "sha512": "421fdd76e4866e7291c8c82884eefef1a3135f7fa7c72128c82ab6c9dffb2cbf4651593a2ea20229e666c3f766dba900f6a8a3dc046f021f5ca405b1f7218830",
          "sha256": "b36b79ffc6a1e10c9f9319e69424f40a09fb9dc530d36a2210441780dd65b3e3",
          "sha1": "546eb9a3894f63d9402a38ab7945eba62f78e146",
          "md5": "84dbf090d485bfc3e3e2166c61434f55"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.8.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-wasm-js-1.8.0-SNAPSHOT.klib",
          "url": "kotlinx-serialization-protobuf-wasm-js-1.8.0-SNAPSHOT.klib",
          "size": 147911,
          "sha512": "421fdd76e4866e7291c8c82884eefef1a3135f7fa7c72128c82ab6c9dffb2cbf4651593a2ea20229e666c3f766dba900f6a8a3dc046f021f5ca405b1f7218830",
          "sha256": "b36b79ffc6a1e10c9f9319e69424f40a09fb9dc530d36a2210441780dd65b3e3",
          "sha1": "546eb9a3894f63d9402a38ab7945eba62f78e146",
          "md5": "84dbf090d485bfc3e3e2166c61434f55"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "kotlinx-serialization-protobuf-wasm-js-1.8.0-SNAPSHOT-sources.jar",
          "url": "kotlinx-serialization-protobuf-wasm-js-1.8.0-SNAPSHOT-sources.jar",
          "size": 32119,
          "sha512": "98054804dc8749a112eb13938e02764ea056eaa2f847b40587438bb48e81e82d3dc567a351e539fe6738bc3580eb92a69f28148ae906c9f3e97318d908f0207f",
          "sha256": "adf0cfb17060e268e803b4ae360d620bac56ba6466d2c0cacdec5f24fbdcc8d9",
          "sha1": "53e0286c92b60e556ea70fdf3d1082bc3a0e6649",
          "md5": "ce1e824ed4bd12f764c10614eb14bb82"
        }
      ]
    }
  ]
}
